(()=>{
'use strict';
const SUPABASE_URL='https://lgzfmoioecixmnivtqan.supabase.co';
const PUBLISHABLE_KEY='sb_publishable_LTCc5iEgOzrH7t8bxvxwOA_aWsHoY8l';
const SESSION_KEY='courtiq_supabase_session';
const E=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function session(){try{return JSON.parse(localStorage.getItem(SESSION_KEY)||'null')}catch(_){return null}}
async function request(path,options={},retry=true){const s=session();if(!s?.access_token)throw new Error('Sign in to manage billing.');const res=await fetch(SUPABASE_URL+path,{...options,headers:{apikey:PUBLISHABLE_KEY,Authorization:'Bearer '+s.access_token,'Content-Type':'application/json',...(options.headers||{})}});let body=null;try{body=await res.json()}catch(_){}if(res.status===401&&retry&&window.CourtIQData?.refreshSession){const ok=await window.CourtIQData.refreshSession();if(ok)return request(path,options,false)}if(!res.ok)throw new Error(body?.message||body?.error||body?.hint||'Billing request failed');return body}
function model(row,requests,role){const pending=(requests||[]).find(x=>x.status==='pending')||null,admin=['admin','gm'].includes(String(role||'').toLowerCase());return {connected:row?.billing_customer_ready===true||row?.payment_provider==='stripe',subscriptionReady:row?.billing_subscription_ready===true,admin,pending,canRequest:admin&&!pending,currentPlan:String(row?.plan_code||''),status:String(row?.status||'')};}
async function load(){const resolved=await window.CourtIQMultiClub?.resolveClub?.();if(!resolved?.club)throw new Error('No active club.');const club=resolved.club;const [rows,members,requests]=await Promise.all([request(`/rest/v1/club_billing_status?select=*&club_id=eq.${Number(club.id)}&limit=1`),request(`/rest/v1/club_members?select=role&club_id=eq.${Number(club.id)}&limit=1`),request(`/rest/v1/plan_upgrade_requests?select=id,requested_plan,status,note,created_at&club_id=eq.${Number(club.id)}&order=created_at.desc&limit=10`)]);if(!rows?.length)throw new Error('Billing status unavailable.');return {club,row:rows[0],role:members?.[0]?.role||'',requests:requests||[]};}
async function requestUpgrade(plan,note=''){const {club}=await load();const allowed=['team','pro','enterprise'];if(!allowed.includes(plan))throw new Error('Unsupported plan.');const body=await request('/rest/v1/plan_upgrade_requests',{method:'POST',headers:{Prefer:'return=representation'},body:JSON.stringify({club_id:Number(club.id),requested_plan:plan,note:String(note||'').slice(0,500)})});return Array.isArray(body)?body[0]:body;}
function planCard(code,title,copy,state){const disabled=!state.canRequest||state.currentPlan===code,button=state.pending?`Request pending: ${E(state.pending.requested_plan)}`:state.currentPlan===code?'Current plan':`Request ${title}`;return `<article class="billPlan"><small>${E(code.toUpperCase())}</small><h3>${E(title)}</h3><p>${E(copy)}</p><button data-plan="${E(code)}" ${disabled?'disabled':''}>${E(button)}</button></article>`}
function render(root,data){const s=model(data.row,data.requests,data.role),provider=data.row.payment_provider?String(data.row.payment_provider).toUpperCase():'NOT CONNECTED',usage=data.row.monthly_game_limit==null?`${data.row.games_used} / ∞`:`${data.row.games_used} / ${data.row.monthly_game_limit}`;root.innerHTML=`<div class="billHero"><div><small>COURTIQ BILLING</small><h2>${E(data.club.name)}</h2><p>${E(data.row.plan_name||data.row.plan_code)} · ${E(String(data.row.status||'').toUpperCase())}</p></div><span>${E(provider)}</span></div><div class="billGrid"><div><small>PLAN</small><b>${E(data.row.plan_name||data.row.plan_code)}</b></div><div><small>GAME USAGE</small><b>${E(usage)}</b></div><div><small>SEATS</small><b>${data.row.seat_limit==null?'∞':E(data.row.seat_limit)}</b></div><div><small>BILLING LINK</small><b>${s.connected?'READY':'PENDING'}</b></div></div>${s.pending?`<p class="billPending">Upgrade request pending: <b>${E(String(s.pending.requested_plan).toUpperCase())}</b> · ${E(new Date(s.pending.created_at).toLocaleDateString('he-IL'))}</p>`:''}${!s.admin?'<p class="billWarn">Only a club Admin/GM can request a commercial plan change.</p>':''}<section><h3>Commercial plans</h3><div class="billPlans">${planCard('team','Team','Core scouting, Coach Brief, Season Memory and up to 150 official games per period.',s)}${planCard('pro','Pro','Higher usage plus Live Intelligence and Video Intelligence entitlements.',s)}${planCard('enterprise','Enterprise','Unlimited/custom deployment, multi-team workspace and API access.',s)}</div></section><p class="billFoot">Stripe payment execution is activated only after the account connector and project secrets are configured. CourtIQ entitlements remain the authorization source of truth.</p>`;root.querySelectorAll('button[data-plan]').forEach(b=>b.onclick=async()=>{if(b.disabled)return;const plan=b.dataset.plan;b.disabled=true;b.textContent='Submitting…';try{await requestUpgrade(plan);const next=await load();render(root,next)}catch(e){b.disabled=false;b.textContent='Try again';alert(e.message)}})}
async function open(){document.getElementById('cqBillingCenter')?.remove();const m=document.createElement('div');m.id='cqBillingCenter';m.className='modal';m.innerHTML='<div class="modalCard billCard"><button class="modalX">×</button><p class="billLoading">Loading billing…</p><div class="billBody"></div></div>';document.body.appendChild(m);m.querySelector('.modalX').onclick=()=>m.remove();m.onclick=e=>{if(e.target===m)m.remove()};try{const data=await load();m.querySelector('.billLoading').remove();render(m.querySelector('.billBody'),data)}catch(e){m.querySelector('.billLoading').textContent=e.message}}
function style(){if(document.getElementById('cqBillingStyle'))return;const s=document.createElement('style');s.id='cqBillingStyle';s.textContent='.billCard{max-width:900px}.billHero{display:flex;justify-content:space-between;gap:16px}.billHero h2{margin:4px 0}.billHero>span{font-size:11px;border:1px solid rgba(255,255,255,.15);border-radius:999px;padding:7px 10px;height:max-content}.billGrid{display:grid;grid-template-columns:repeat(4,1fr);gap:8px;margin:16px 0}.billGrid>div,.billPlan{border:1px solid rgba(255,255,255,.1);border-radius:12px;padding:13px;background:rgba(255,255,255,.03)}.billGrid small,.billPlan small{display:block;color:#8298ad;font-size:10px}.billGrid b{font-size:18px}.billPlans{display:grid;grid-template-columns:repeat(3,1fr);gap:10px}.billPlan h3{margin:4px 0}.billPlan p{color:#91a6ba;min-height:58px}.billPlan button{width:100%;padding:9px;border-radius:8px;border:1px solid rgba(255,255,255,.16);background:#14283b;color:#fff;cursor:pointer}.billPlan button:disabled{opacity:.45;cursor:not-allowed}.billPending,.billWarn,.billFoot{padding:11px;border-radius:9px;background:rgba(255,255,255,.04);color:#9db0c2}.billPending{border-right:3px solid #49c986}.billWarn{border-right:3px solid #d79b4b}.billFoot{font-size:11px}@media(max-width:720px){.billGrid,.billPlans{grid-template-columns:1fr 1fr}}@media(max-width:480px){.billGrid,.billPlans{grid-template-columns:1fr}}';document.head.appendChild(s)}
function inject(){style();const p=document.querySelector('.pills');if(!p||document.getElementById('billingFlow'))return;const b=document.createElement('button');b.id='billingFlow';b.className='importBtn';b.textContent='BILLING · UPGRADE';b.onclick=open;p.appendChild(b)}
const Core={model};if(typeof window!=='undefined'){window.CourtIQBilling={open,load,requestUpgrade,Core};if(typeof document!=='undefined'){let t;const boot=()=>inject();new MutationObserver(()=>{clearTimeout(t);t=setTimeout(boot,80)}).observe(document.documentElement,{childList:true,subtree:true});if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();}}
})();
