/* Arithmetic shooting counterfactuals; no forecasts or game-state inference. */
(function(root){
 'use strict';
 const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const integer=v=>['number','string'].includes(typeof v)&&String(v).trim()!==''&&Number.isInteger(Number(v))&&Number(v)>=0?Number(v):null;
 const types=[{key:'two',made:'two_pm',attempts:'two_pa',label:'2-point makes',weight:2},{key:'three',made:'three_pm',attempts:'three_pa',label:'3-point makes',weight:3},{key:'ft',made:'ftm',attempts:'fta',label:'Free throws made',weight:1}];
 const pct=(a,b)=>b>0?100*a/b:null;
 function baseline(G,side='home'){
  if(!['home','away'].includes(side))throw new Error('Choose a focus team.');
  const r=G.raw?.[side],points=integer(side==='home'?G.hs:G.as),opponent=integer(side==='home'?G.as:G.hs);
  if(!r||points==null||opponent==null)throw new Error('A complete team shooting box score and both final scores are required.');
  const shots={};for(const t of types){const made=integer(r[t.made]),attempts=integer(r[t.attempts]);if(made==null||attempts==null||made>attempts)throw new Error('Missing or invalid '+t.label.toLowerCase()+' totals.');shots[t.key]={made,attempts,weight:t.weight};}
  if(types.reduce((n,t)=>n+shots[t.key].made*t.weight,0)!==points)throw new Error('Shooting totals do not reconcile with this team’s final score. Review the source before exploring scenarios.');
  return {team:G[side],side,points,opponent,shots};
 }
 function simulate(G,side='home',changes={}){
  const base=baseline(G,side),shots={},contributions={};let swing=0;
  for(const t of types){const d=changes[t.key]??0,b=base.shots[t.key];if(typeof d!=='number'||!Number.isInteger(d)||d < -b.made||d>b.attempts-b.made)throw new Error('Change to '+t.label.toLowerCase()+' exceeds recorded attempts.');shots[t.key]={...b,made:b.made+d};contributions[t.key]=t.weight*d;swing+=contributions[t.key];}
  const score=base.points+swing,fga=shots.two.attempts+shots.three.attempts;
  return {base,shots,score,swing,margin:score-base.opponent,contributions,efg:pct(shots.two.made+1.5*shots.three.made,fga),ts:pct(score,2*(fga+.44*shots.ft.attempts)),neededToLead:Math.max(0,base.opponent-score+1)};
 }
 function preset(G,side,name){const b=baseline(G,side),changes={two:0,three:0,ft:0};if(name==='ft80')changes.ft=Math.max(0,Math.ceil(.8*b.shots.ft.attempts)-b.shots.ft.made);else if(name==='oneThree')changes.three=Math.min(1,b.shots.three.attempts-b.shots.three.made);else if(name==='twoTwos')changes.two=Math.min(2,b.shots.two.attempts-b.shots.two.made);return changes;}
 const value=x=>x==null?'—':x.toFixed(1)+'%';
 function summary(G,side,changes){const r=simulate(G,side,changes);return 'CourtIQ Decision Lab · HYPOTHETICAL SCENARIO\n'+G.home+' '+G.hs+'–'+G.as+' '+G.away+' · '+(G.date||'Date unavailable')+'\nFocus: '+r.base.team+'\n'+types.map(t=>t.label+': '+r.base.shots[t.key].made+'/'+r.shots[t.key].attempts+' → '+r.shots[t.key].made+'/'+r.shots[t.key].attempts+' ('+(changes[t.key]>=0?'+':'')+(changes[t.key]||0)+' makes)').join('\n')+'\nScenario points: '+r.score+' · margin: '+(r.margin>=0?'+':'')+r.margin+' · swing: '+(r.swing>=0?'+':'')+r.swing+'\neFG%: '+value(r.efg)+' · TS%: '+value(r.ts)+'\nAssumptions: shot attempts, opponent points and all other game events stay fixed. This is arithmetic sensitivity, not a forecast, tactical effect or a revision of the official result. TS uses 0.44 × free-throw attempts.';}
 function render(G){return '<section class="gameViewPanel decisionLab" data-game-view="lab"><div class="viewTitle"><div><small>BOX SCORE → WHAT IF?</small><h3>Decision Lab · מעבדת תרחישים</h3></div><span>HYPOTHETICAL · OFFICIAL RESULT UNCHANGED</span></div><p class="labIntro">How sensitive was the result to shooting conversion? Explore different makes with the same recorded shot attempts.</p><label class="labTeamLabel">Focus team<select class="labTeam"><option value="home">'+esc(G.home)+'</option><option value="away">'+esc(G.away)+'</option></select></label><div class="labWorkspace"></div></section>';}
 function mount(G,scope=root.document){const el=scope?.querySelector('.decisionLab');if(!el)return;let side='home',changes={two:0,three:0,ft:0};
  const draw=()=>{const box=el.querySelector('.labWorkspace');let b;try{b=baseline(G,side);}catch(e){box.innerHTML='<div class="card emptyView"><b>Scenario unavailable</b><span>'+esc(e.message)+'</span></div>';return;}
   box.innerHTML='<div class="labPresets"><button type="button" class="importBtn" data-lab-preset="ft80">FREE THROWS TO AT LEAST 80%</button><button type="button" class="importBtn" data-lab-preset="oneThree">ONE MORE 3-POINTER</button><button type="button" class="importBtn" data-lab-preset="twoTwos">TWO MORE 2-POINTERS</button><button type="button" class="importBtn" data-lab-preset="reset">RESET TO ACTUAL</button></div><div class="labLayout"><div class="card box labControls"><h3>Change makes, keep attempts</h3>'+types.map(t=>{const shot=b.shots[t.key],misses=shot.attempts-shot.made;return '<label>'+t.label+'<small>Actual '+shot.made+'/'+shot.attempts+' · '+misses+' misses available</small><input type="range" data-lab-change="'+t.key+'" aria-label="Change '+t.label.toLowerCase()+'" min="'+(-shot.made)+'" max="'+misses+'" step="1" value="'+changes[t.key]+'"><output data-lab-output="'+t.key+'"></output></label>';}).join('')+'</div><div class="card box labResults" aria-live="polite"></div></div><p class="metricNote labAssumptions">This is a shooting counterfactual, not a prediction. Opponent points, shot volume and all other events are held fixed. In a real game, different makes also change rebounds, transitions and subsequent possessions. No turnover or rebound effect is inferred.</p><details class="labCopy"><summary>Copy scenario for a coaching discussion</summary><p>This text labels every assumption and does not change the game record.</p><textarea readonly aria-label="Scenario summary"></textarea><button type="button" class="importBtn labSelectSummary">SELECT SCENARIO TEXT</button><p class="labCopyStatus" role="status"></p></details>';
   const update=()=>{const r=simulate(G,side,changes),actual=simulate(G,side),result=box.querySelector('.labResults');types.forEach(t=>{box.querySelector('[data-lab-output="'+t.key+'"]').textContent=(changes[t.key]>=0?'+':'')+changes[t.key]+' makes · '+r.shots[t.key].made+'/'+r.shots[t.key].attempts+' · '+(r.contributions[t.key]>=0?'+':'')+r.contributions[t.key]+' pts';});result.innerHTML='<small>SCENARIO · '+esc(b.team)+'</small><div class="labScore">'+r.score+' <span>vs '+b.opponent+'</span></div><div class="reportKpis"><div><small>POINT SWING</small><b>'+(r.swing>=0?'+':'')+r.swing+'</b></div><div><small>SCENARIO MARGIN</small><b>'+(r.margin>=0?'+':'')+r.margin+'</b></div></div><p class="labLead">'+(r.neededToLead?'Needs '+r.neededToLead+' more points to lead under these fixed-score assumptions.':'Focus team leads in this scenario.')+'</p><div class="playerScroll"><table class="stats"><thead><tr><th>Metric</th><th>Actual</th><th>Scenario</th></tr></thead><tbody>'+types.map(t=>'<tr><td>'+t.label+'</td><td>'+b.shots[t.key].made+'/'+b.shots[t.key].attempts+'</td><td>'+r.shots[t.key].made+'/'+r.shots[t.key].attempts+'</td></tr>').join('')+'<tr><td>eFG%</td><td>'+value(actual.efg)+'</td><td>'+value(r.efg)+'</td></tr><tr><td>TS%</td><td>'+value(actual.ts)+'</td><td>'+value(r.ts)+'</td></tr></tbody></table></div><p class="metricNote">Point swing = 2 × change in 2P makes + 3 × change in 3P makes + change in FT makes. TS denominator = 2 × (FGA + 0.44 × FTA).</p>';box.querySelector('textarea').value=summary(G,side,changes);};
   box.querySelectorAll('[data-lab-change]').forEach(field=>field.oninput=()=>{changes[field.dataset.labChange]=Number(field.value);update();});box.querySelectorAll('[data-lab-preset]').forEach(btn=>btn.onclick=()=>{changes=preset(G,side,btn.dataset.labPreset);draw();});box.querySelector('.labSelectSummary').onclick=()=>{const field=box.querySelector('textarea');field.focus();field.select();box.querySelector('.labCopyStatus').textContent='Scenario text selected. Copy it to your coaching notes.';};update();};
  el.querySelector('.labTeam').onchange=e=>{side=e.target.value;changes={two:0,three:0,ft:0};draw();};draw();return {reset:()=>{changes={two:0,three:0,ft:0};draw();}};
 }
 const api={baseline,simulate,preset,summary,render,mount};root.CourtIQDecisionLab=api;if(typeof module!=='undefined'&&module.exports)module.exports=api;
})(typeof window!=='undefined'?window:globalThis);
