/* Player shooting volume/efficiency: a descriptive single-game sample. */
(function(root){
 'use strict';
 const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const count=v=>['number','string'].includes(typeof v)&&String(v).trim()!==''&&Number.isInteger(Number(v))&&Number(v)>=0?Number(v):null;
 const pct=(a,b)=>b>0?100*a/b:null,display=v=>v==null?'—':v.toFixed(1)+'%';
 function analyze(G,side='home',minimum=5,sort='fga'){
  if(!['home','away'].includes(side))throw new Error('Choose a team.');if(!Number.isInteger(minimum)||minimum<0)throw new Error('Minimum attempts must be a nonnegative integer.');
  const source=Array.isArray(G.players?.[side])?G.players[side]:[],rows=[],issues=[],names=new Map();for(const p of source){const name=String(p?.name||'').trim();if(name)names.set(name,(names.get(name)||0)+1);}
  source.forEach((p,index)=>{const name=String(p?.name||'').trim();const fail=reason=>issues.push({name:name||'Unnamed row '+(index+1),reason});if(!name||names.get(name)!==1){fail('Missing or duplicate player name.');return;}
   const raw={};for(const key of ['points','two_pm','two_pa','three_pm','three_pa','ftm','fta']){raw[key]=count(p[key]);if(raw[key]==null){fail('Missing or invalid shooting totals.');return;}}
   if(raw.two_pm>raw.two_pa||raw.three_pm>raw.three_pa||raw.ftm>raw.fta){fail('Makes exceed attempts.');return;}
   if(2*raw.two_pm+3*raw.three_pm+raw.ftm!==raw.points){fail('Shooting totals do not reconcile with player points.');return;}
   const fga=raw.two_pa+raw.three_pa;rows.push({index,name,...raw,fga,efg:pct(raw.two_pm+1.5*raw.three_pm,fga),ts:pct(raw.points,2*(fga+.44*raw.fta)),share:null});
  });
  let team=null,teamError='';try{team=root.CourtIQDecisionLab?.baseline(G,side);if(!team)teamError='Team shooting totals unavailable.';}catch(e){teamError=e.message;}
  const teamFga=team?team.shots.two.attempts+team.shots.three.attempts:null,teamEfg=team?pct(team.shots.two.made+1.5*team.shots.three.made,teamFga):null;
  for(const p of rows)p.share=teamFga>0?pct(p.fga,teamFga):null;
  const totals=rows.reduce((s,p)=>{for(const k of ['points','two_pm','two_pa','three_pm','three_pa','ftm','fta'])s[k]=(s[k]||0)+p[k];return s;},{});
  const reconciled=Boolean(team&&source.length&&issues.length===0&&totals.points===team.points&&['two','three','ft'].every(k=>totals[k==='ft'?'ftm':k+'_pm']===team.shots[k].made&&totals[k==='ft'?'fta':k+'_pa']===team.shots[k].attempts));
  const key=['fga','efg','points'].includes(sort)?sort:'fga',visible=rows.filter(p=>p.fga>=minimum).sort((a,b)=>(b[key]??-Infinity)-(a[key]??-Infinity)||a.name.localeCompare(b.name));
  return {team:G[side],rows,issues,sourceCount:source.length,minimum,visible,plotted:visible.filter(p=>p.efg!=null),teamFga,teamEfg,reconciled,teamError,below:rows.filter(p=>p.fga<minimum).length};
 }
 function summary(G,side){const r=analyze(G,side);return '\nPLAYER SHOOTING SCAN · MINIMUM 5 FGA (REVIEW FILTER, NOT CONFIDENCE)\n'+r.rows.length+'/'+r.sourceCount+' valid player rows · '+r.issues.length+' flagged · team reconciliation '+(r.reconciled?'passed':'unavailable or requires review')+'\n'+r.visible.map(p=>p.name+': '+p.points+' pts · '+p.fga+' FGA · eFG '+display(p.efg)+' · TS '+display(p.ts)+' · share of reported team FGA '+display(p.share)).join('\n')+'\nFGA share is not Usage. eFG = (2PM + 1.5 × 3PM) / FGA; TS = PTS / [2 × (FGA + 0.44 × FTA)]. These rates describe one game and do not establish overall player impact.';}
 function mount(G,side,el){if(!el)return;let minimum=5,sort='fga',selected=null;
  const draw=()=>{const r=analyze(G,side,minimum,sort);if(!r.sourceCount){el.innerHTML='<section class="card box playerScan"><small>PLAYER SHOOTING SCAN</small><h3>Player shooting map · מפת קליעה</h3><p>Player shooting totals are unavailable for this game. Import a complete player box score; team totals cannot supply individual attempts.</p></section>';return;}
   if(!r.visible.some(p=>p.index===selected))selected=r.visible[0]?.index??null;
   const maxX=Math.max(1,...r.plotted.map(p=>p.fga)),x=v=>55+440*v/maxX,y=v=>275-240*v/150;
   const chart='<svg class="playerScanChart" viewBox="0 0 560 330" role="group" aria-label="Player field-goal attempts versus effective field-goal percentage">'+[0,50,100,150].map(v=>'<line x1="55" x2="495" y1="'+y(v)+'" y2="'+y(v)+'" class="scanGrid"/><text x="45" y="'+(y(v)+4)+'" text-anchor="end">'+v+'%</text>').join('')+'<line x1="55" y1="275" x2="495" y2="275" class="scanGrid"/><text x="55" y="296">0</text><text x="495" y="296" text-anchor="end">'+maxX+'</text><text x="275" y="320" text-anchor="middle">Field-goal attempts (FGA)</text><text x="55" y="19">eFG% · can exceed 100%</text>'+(r.teamEfg!=null&&r.reconciled?'<line x1="55" x2="495" y1="'+y(r.teamEfg)+'" y2="'+y(r.teamEfg)+'" class="scanTeamLine"/><text x="495" y="'+Math.max(18,y(r.teamEfg)-6)+'" text-anchor="end">Team '+display(r.teamEfg)+'</text>':'')+r.plotted.map(p=>'<g class="scanPoint" role="button" tabindex="0" data-player="'+p.index+'" aria-label="'+esc(p.name)+', '+p.fga+' attempts, eFG '+display(p.efg)+'"><title>'+esc(p.name)+' · '+p.fga+' FGA · '+display(p.efg)+'</title><circle cx="'+x(p.fga)+'" cy="'+y(p.efg)+'" r="10"/><text x="'+x(p.fga)+'" y="'+(y(p.efg)+4)+'" text-anchor="middle">'+(p.index+1)+'</text></g>').join('')+'</svg>';
   el.innerHTML='<section class="card box playerScan"><div class="sectionhead"><div><small>SHOT VOLUME × SHOOTING CONVERSION · 1 GAME</small><h3>Player shooting map · מפת קליעה</h3></div><span>'+esc(r.team)+'</span></div><div class="playerScanControls"><label>Minimum FGA<input class="scanMinimum" type="number" min="0" step="1" value="'+minimum+'"></label><label>Sort players<select class="scanSort"><option value="fga">Attempts</option><option value="efg">eFG%</option><option value="points">Points</option></select></label></div><p class="scanCoverage" role="status">'+r.visible.length+' shown · '+r.below+' below the FGA filter · '+r.issues.length+' flagged of '+r.sourceCount+' rows. '+(r.reconciled?'Player shooting totals reconcile with team totals.':'Team/player shooting reconciliation is unavailable or requires review; the team reference line is hidden.')+'</p><div class="playerScanLayout"><div>'+chart+'<p class="metricNote">Each numbered dot is a player with known eFG%. Same-coordinate dots can overlap; use the player table to select every player. The FGA filter is a review threshold, not statistical confidence.</p></div><div class="scanPlayerCard" aria-live="polite"></div></div><div class="playerScroll"><table class="stats scanTable"><thead><tr><th>Player</th><th>PTS</th><th>FGA</th><th>Team FGA share</th><th>eFG%</th><th>TS%</th></tr></thead><tbody>'+r.visible.map(p=>'<tr><td><button type="button" class="importBtn scanPlayerButton" data-player="'+p.index+'">'+(p.index+1)+'. '+esc(p.name)+'</button></td><td>'+p.points+'</td><td>'+p.fga+'</td><td>'+display(p.share)+'</td><td>'+display(p.efg)+'</td><td>'+display(p.ts)+'</td></tr>').join('')+'</tbody></table></div>'+(r.visible.length?'':'<p>No valid players match this minimum. Lower the FGA filter to inspect smaller samples.</p>')+(r.issues.length?'<details class="scanIssues"><summary>'+r.issues.length+' rows need review</summary>'+r.issues.map(i=>'<p>'+esc(i.name)+' · '+esc(i.reason)+'</p>').join('')+'</details>':'')+'<p class="metricNote">FGA share is the share of recorded team field-goal attempts, not Usage. Scoring, shooting rates and attempt volume are descriptive; minutes, defensive value, lineup effects and shot difficulty are not measured by this map. Missing denominators stay —.</p></section>';
   const select=index=>{selected=index;const p=r.visible.find(p=>p.index===index),card=el.querySelector('.scanPlayerCard');el.querySelectorAll('[data-player]').forEach(node=>{const active=Number(node.dataset.player)===index;node.classList.toggle('selected',active);node.setAttribute('aria-pressed',String(active));});card.innerHTML=p?'<small>SELECTED PLAYER · '+(p.fga<5?'FEWER THAN 5 FGA':'ONE-GAME SAMPLE')+'</small><h3>'+esc(p.name)+'</h3><div class="reportKpis"><div><small>FIELD-GOAL ATTEMPTS</small><b>'+p.fga+'</b></div><div><small>eFG%</small><b>'+display(p.efg)+'</b></div><div><small>TS%</small><b>'+display(p.ts)+'</b></div><div><small>TEAM FGA SHARE</small><b>'+display(p.share)+'</b></div></div><p>2P: '+p.two_pm+'/'+p.two_pa+' · 3P: '+p.three_pm+'/'+p.three_pa+' · FT: '+p.ftm+'/'+p.fta+' · '+p.points+' points.</p><p class="metricNote">eFG% = (2PM + 1.5 × 3PM) / FGA. TS% = PTS / [2 × (FGA + 0.44 × FTA)]. Free throws affect TS, not eFG.</p>':'<p>Select a player after lowering the minimum or reviewing incomplete records.</p>';};
   el.querySelector('.scanSort').querySelectorAll('option').forEach(option=>{option.selected=option.value===sort;});el.querySelector('.scanSort').onchange=e=>{sort=e.target.value;draw();};el.querySelector('.scanMinimum').onchange=e=>{const n=count(e.target.value);if(n==null){e.target.value=minimum;return;}minimum=n;draw();};el.querySelectorAll('[data-player]').forEach(node=>{node.onclick=()=>select(Number(node.dataset.player));if(node.classList.contains('scanPoint'))node.onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();select(Number(node.dataset.player));}};});select(selected);
  };draw();return {draw};
 }
 const api={analyze,summary,mount};root.CourtIQPlayerScan=api;if(typeof module!=='undefined'&&module.exports)module.exports=api;
})(typeof window!=='undefined'?window:globalThis);
