(function(){
const STORE="courtiq_video_room_v1";
const esc=v=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
function parseYouTube(input){try{const u=new URL(input);if(u.hostname==="youtu.be")return u.pathname.slice(1).split("/")[0];if(/(^|\.)youtube\.com$/.test(u.hostname)){if(u.pathname==="/watch")return u.searchParams.get("v");if(u.pathname.startsWith("/embed/"))return u.pathname.split("/")[2];}}catch(_){}return null}
function load(){try{return JSON.parse(localStorage.getItem(STORE)||"{}")}catch(_){return {}}}
function save(x){localStorage.setItem(STORE,JSON.stringify(x))}
function secs(v){const p=String(v||"").trim().split(":").map(Number);return p.length===2&&p.every(Number.isFinite)?p[0]*60+p[1]:null}
function clockElapsed(period,clock){const left=secs(clock);if(left==null)return null;const q=Number(period||1),len=q<=4?600:300;return (Math.max(1,q)-1)*600+(len-left)}
function videoForPbp(anchor,period,clock){if(!anchor)return null;const a=clockElapsed(anchor.period,anchor.clock),e=clockElapsed(period,clock);if(a==null||e==null)return null;return Math.max(0,Math.round(Number(anchor.videoSeconds)+(e-a)))}
function ytAt(id,seconds){return "https://youtu.be/"+encodeURIComponent(id)+"?t="+Math.max(0,Math.round(seconds||0))+"s"}
function confidence(e){let n=25;if(e.tag&&e.tag!=="Other")n+=15;if(e.coverage)n+=15;if(e.ballHandler)n+=10;if(e.screener)n+=10;if((e.players||"").split(",").filter(Boolean).length>=5)n+=15;if(e.note)n+=5;if(e.source==="official-pbp")n+=5;return Math.min(100,n)}
function status(e){const n=confidence(e);return n>=85?"VERIFIED":n>=60?"ASSISTED":"REVIEW"}
function classifyPbp(e){const d=String(e.description||e.action||"").toLowerCase();let tag="Other",points=null;if(/turnover|איבוד/.test(d))tag="Turnover";else if(/rebound|ריבאונד/.test(d))tag="Rebound";else if(/free throw|עונשין/.test(d))tag="Free Throw";else if(/3pt|3 pt|three point|שלוש/.test(d)){tag="Shot · 3PT";points=/made|makes|קלע/.test(d)?3:0}else if(/2pt|2 pt|layup|dunk|jumper|שתיים/.test(d)){tag="Shot · 2PT";points=/made|makes|קלע/.test(d)?2:0}else if(/foul|עבירה/.test(d))tag="Foul";return {tag,points}}
function importPbp(events){const s=load();if(!s.videoId)return {added:0,reason:"video"};const seen=new Set((s.events||[]).filter(x=>x.source==="official-pbp").map(x=>[x.period,x.gameClock,x.note].join("|")));let added=0;(events||[]).forEach(e=>{const key=[e.period,e.clock,e.description||e.action].join("|");if(seen.has(key))return;const v=videoForPbp(s.anchor,e.period,e.clock),a=classifyPbp(e);(s.events??=[]).push({time:v==null?"":Math.floor(v/60)+":"+String(v%60).padStart(2,"0"),period:e.period,gameClock:e.clock,tag:a.tag,note:e.description||e.action||"",kind:a.points==null?"evidence":"possession",points:a.points,offense:e.team||"",players:e.player||"",coverage:"",ballHandler:e.player||"",screener:"",source:"official-pbp",createdAt:new Date().toISOString()});added++});save(s);return {added}}
function assistFromEvidence(e){const text=((e.note||"")+" "+(e.tag||"")).toLowerCase();let coverage=e.coverage||"";if(!coverage){if(/switch/.test(text))coverage="Switch";else if(/drop/.test(text))coverage="Drop";else if(/trap|blitz/.test(text))coverage="Blitz / Trap";else if(/hedge|show/.test(text))coverage="Hedge / Show";else if(/ice|down/.test(text))coverage="ICE / Down";else if(/zone/.test(text))coverage="Zone"}return {...e,coverage,assistApplied:coverage!==e.coverage}}
function openRoom(){
 const state=load(),modal=document.createElement("div");modal.className="modal";
 modal.innerHTML=`<div class="modalCard compareModal"><button class="modalX">×</button><small class="eyebrow">COURTIQ · VIDEO EVIDENCE ROOM</small><h2>Import Game Video</h2><p>Paste a YouTube game link. CourtIQ keeps video evidence separate from verified box-score facts: timestamps and tags are evidence; tactical conclusions require analyst review.</p><div class="importFields"><input id="videoUrl" placeholder="https://youtu.be/..." value="${esc(state.url||"")}"></div><div id="videoStatus" class="impStatus"></div><button id="loadVideo" class="runImport">LOAD VIDEO</button><div id="videoWorkspace"></div></div>`;
 document.body.appendChild(modal);modal.querySelector(".modalX").onclick=()=>modal.remove();modal.onclick=e=>{if(e.target===modal)modal.remove()};
 const draw=()=>{const s=load(),box=modal.querySelector("#videoWorkspace");if(!s.videoId){box.innerHTML="";return}
 const events=s.events||[]; const poss=events.filter(e=>e.kind==="possession"); const pts=poss.reduce((n,e)=>n+Number(e.points||0),0), ppp=poss.length?(pts/poss.length).toFixed(2):"—";
 const groups=Object.values(poss.reduce((m,e)=>{const k=(e.tag||"Other")+(e.coverage?" · vs "+e.coverage:"");(m[k]??={tag:k,rows:[],points:0});m[k].rows.push(e);m[k].points+=Number(e.points||0);return m},{})).sort((a,b)=>b.rows.length-a.rows.length);
 const tactical=groups.map(g=>({...g,ppp:g.rows.length?(g.points/g.rows.length).toFixed(2):"—",scoreRate:g.rows.length?Math.round(g.rows.filter(x=>Number(x.points)>0).length/g.rows.length*100):0,confidence:g.rows.length>=10?"STRONG SAMPLE":g.rows.length>=5?"DEVELOPING":"SMALL SAMPLE"}));
 box.innerHTML=`<div style="position:relative;padding-top:56.25%;margin:16px 0"><iframe id="cqVideo" style="position:absolute;inset:0;width:100%;height:100%;border:0;border-radius:12px" src="https://www.youtube.com/embed/${esc(s.videoId)}?enablejsapi=1" allow="accelerometer;autoplay;clipboard-write;encrypted-media;gyroscope;picture-in-picture" allowfullscreen></iframe></div>
 <div class="schema"><b>VIDEO LOADED · ${esc(s.videoId)}</b><br>Use the YouTube clock, enter a timestamp, then tag the possession. CourtIQ does not claim automatic computer-vision detection in this browser build.</div>
 <h3>Official PBP ↔ Video Sync</h3><div class="schema">Create one anchor: choose a visible game-clock moment and enter its YouTube timestamp. CourtIQ can then map official Play-by-Play events to video time. Re-sync at quarter breaks if the broadcast contains long edits.</div><div class="importFields"><input id="anchorPeriod" type="number" min="1" max="8" placeholder="Period · 1"><input id="anchorClock" placeholder="Game clock · 09:42"><input id="anchorVideo" placeholder="Video time · 03:18"></div><button id="saveAnchor" class="importBtn">SAVE SYNC ANCHOR</button><div id="syncPreview"></div><div class="reportKpis"><div><small>TAGGED POSSESSIONS</small><b>${poss.length}</b></div><div><small>POINTS</small><b>${pts}</b></div><div><small>PPP</small><b>${ppp}</b></div><div><small>EVIDENCE</small><b>${events.length}</b></div></div><div class="importFields"><input id="evTime" placeholder="Timestamp · 12:34"><select id="evTag"><option>Pick & Roll</option><option>Transition</option><option>Turnover</option><option>Shot Quality</option><option>Offensive Rebound</option><option>Post Up</option><option>Isolation</option><option>ATO / Set Play</option><option>Defense</option><option>Other</option></select><select id="evResult"><option value="">Evidence only</option><option value="0">Possession · 0 pts</option><option value="1">Possession · 1 pt</option><option value="2">Possession · 2 pts</option><option value="3">Possession · 3 pts</option></select><input id="evOffense" placeholder="Offense · team"><select id="evCoverage"><option value="">Coverage · unknown</option><option>Drop</option><option>Switch</option><option>Hedge / Show</option><option>Blitz / Trap</option><option>ICE / Down</option><option>Under</option><option>Zone</option><option>Other</option></select><input id="evBallHandler" placeholder="Ball handler"><input id="evScreener" placeholder="Screener"><input id="evPlayers" placeholder="5-man lineup · comma separated"><input id="evNote" placeholder="Evidence note · what happened?"></div><button id="autoAssist" class="importBtn">AUTO ASSIST</button><button id="addEvidence" class="runImport">ADD VIDEO EVIDENCE</button>
 <h3>Tactical Findings · Evidence-backed</h3><div class="gameLibraryGrid">${tactical.length?tactical.map((g,gi)=>`<div class="card box"><small>${esc(g.confidence)}</small><h3>${esc(g.tag)}</h3><div class="reportKpis"><div><small>SAMPLE</small><b>${g.rows.length}</b></div><div><small>PPP</small><b>${g.ppp}</b></div><div><small>SCORE RATE</small><b>${g.scoreRate}%</b></div></div><button class="importBtn" data-evidence-group="${gi}">VIEW ${g.rows.length} EVIDENCE CLIPS</button><div data-evidence-list="${gi}" hidden class="videoList">${g.rows.map((e,i)=>{const t=secs(e.time);return `<div class="videoItem"><span>${i+1}</span><a href="${esc(ytAt(s.videoId,t))}" target="_blank" rel="noopener">${esc(e.time)} · ${esc(e.points)} pts</a> — ${esc(e.note||"Tagged possession")}</div>`}).join("")}</div></div>`).join(""):'<div class="schema">Tag possessions to generate tactical findings. CourtIQ will show sample size before any tactical interpretation.</div>'}</div><h3>Evidence Timeline</h3><div class="videoList">${events.length?events.map((e,i)=>`<div class="videoItem"><span>${i+1}</span><b>${esc(e.time)} · ${esc(e.tag)}</b>${e.kind==="possession"?` · ${esc(e.points)} PTS · ${esc(e.offense||"team?")}`:""} · <small>${status(e)} ${confidence(e)}%</small> — ${esc(e.note||"No note")}${e.coverage?`<br><small>Coverage: ${esc(e.coverage)}</small>`:""}${e.ballHandler?` · <small>BH: ${esc(e.ballHandler)}</small>`:""}${e.screener?` · <small>SC: ${esc(e.screener)}</small>`:""}${e.players?`<br><small>Lineup: ${esc(e.players)}</small>`:""} <button data-del="${i}" class="importBtn">×</button></div>`).join(""):'<div class="schema">No tagged possessions yet.</div>'}</div>
 <div class="metricNote">Evidence status: analyst-tagged video. Link these timestamps to official Play-by-Play/box-score events before publishing tactical claims.</div>`;
 box.querySelector("#saveAnchor").onclick=()=>{const period=Number(box.querySelector("#anchorPeriod").value),clock=box.querySelector("#anchorClock").value.trim(),video=box.querySelector("#anchorVideo").value.trim(),vs=secs(video);if(!period||secs(clock)==null||vs==null){modal.querySelector("#videoStatus").textContent="Enter period, game clock MM:SS and video time MM:SS.";return}const x=load();x.anchor={period,clock,videoSeconds:vs};save(x);modal.querySelector("#videoStatus").textContent="PBP ↔ video anchor saved.";draw()};
 const preview=box.querySelector("#syncPreview"); if(s.anchor) preview.innerHTML='<div class="insight"><b>SYNC ACTIVE</b> · Q'+esc(s.anchor.period)+' '+esc(s.anchor.clock)+' = video '+Math.floor(s.anchor.videoSeconds/60)+':'+String(s.anchor.videoSeconds%60).padStart(2,"0")+'</div>';
 box.querySelector("#autoAssist").onclick=()=>{const tag=box.querySelector("#evTag").value,note=box.querySelector("#evNote").value.trim(),coverage=box.querySelector("#evCoverage").value;const a=assistFromEvidence({tag,note,coverage});if(a.coverage&&!coverage)box.querySelector("#evCoverage").value=a.coverage;modal.querySelector("#videoStatus").textContent=a.assistApplied?"Auto Assist suggested coverage from the analyst note. Review before saving.":"No safe additional inference found. Add PBP/roster evidence or review manually."};
 box.querySelector("#addEvidence").onclick=()=>{const time=box.querySelector("#evTime").value.trim(),tag=box.querySelector("#evTag").value,note=box.querySelector("#evNote").value.trim(),result=box.querySelector("#evResult").value,offense=box.querySelector("#evOffense").value.trim(),players=box.querySelector("#evPlayers").value.trim(),coverage=box.querySelector("#evCoverage").value,ballHandler=box.querySelector("#evBallHandler").value.trim(),screener=box.querySelector("#evScreener").value.trim();if(!/^\d{1,3}:\d{2}$/.test(time)){modal.querySelector("#videoStatus").textContent="Enter timestamp as MM:SS, for example 12:34.";return}const x=load();(x.events??=[]).push({time,tag,note,kind:result===""?"evidence":"possession",points:result===""?null:Number(result),offense,players,coverage,ballHandler,screener,source:"analyst-video",createdAt:new Date().toISOString()});save(x);modal.querySelector("#videoStatus").textContent="Video evidence saved locally.";draw()};
 box.querySelectorAll("[data-evidence-group]").forEach(b=>b.onclick=()=>{const el=box.querySelector('[data-evidence-list="'+b.dataset.evidenceGroup+'"]');el.hidden=!el.hidden});
 box.querySelectorAll("[data-del]").forEach(b=>b.onclick=()=>{const x=load();x.events.splice(Number(b.dataset.del),1);save(x);draw()});
 };
 modal.querySelector("#loadVideo").onclick=()=>{const url=modal.querySelector("#videoUrl").value.trim(),id=parseYouTube(url);if(!id){modal.querySelector("#videoStatus").textContent="Paste a valid YouTube video URL.";return}const old=load();save({...old,url,videoId:id,events:old.videoId===id?(old.events||[]):[]});modal.querySelector("#videoStatus").textContent="Video connected to CourtIQ Video Room.";draw()};draw();
}
function install(){const bar=document.querySelector(".pills");if(bar&&!document.querySelector("#videoImport")){const b=document.createElement("button");b.id="videoImport";b.className="importBtn primaryAction";b.textContent="VIDEO IMPORT";b.onclick=openRoom;bar.appendChild(b)}
 document.querySelectorAll(".menu div").forEach(x=>{if(x.textContent.includes("Video Room")&&!x.dataset.videoBound){x.dataset.videoBound="1";x.addEventListener("click",openRoom)}})}
new MutationObserver(install).observe(document.documentElement,{childList:true,subtree:true});install();
window.CourtIQVideo={open:openRoom,parseYouTube,importPbp,videoForPbp:(period,clock)=>{const s=load(),t=videoForPbp(s.anchor,period,clock);return t==null?null:{seconds:t,url:ytAt(s.videoId,t)}},state:load};
})();