(function(){
const LEGACY_STORE="courtiq_video_room_v1",STORE_PREFIX="courtiq_video_room_v2:";
let gameKey="",gameLabel="";
function identity(G){
 if(!G)return "";
 const source=G.sourceUrl||G.source_url;
 if(source){try{const u=new URL(source);u.hash="";for(const k of [...u.searchParams.keys()])if(k.startsWith("utm_"))u.searchParams.delete(k);u.searchParams.sort();return "source:"+u.href.replace(/\/$/,"");}catch(_){}}
 if(G._dbId)return "saved:"+G._dbId;
 return "game:"+JSON.stringify([G.comp||"",G.date||"",G.home||"",G.away||"",G.id||""]);
}
function setGame(G){const next=identity(G);if(next!==gameKey)document.querySelectorAll('.cqVideoRoom').forEach(x=>x.remove());gameKey=next;gameLabel=G?G.home+" vs "+G.away+" · "+(G.date||""):"Select a game first";}
function legacy(){try{return JSON.parse(localStorage.getItem(LEGACY_STORE)||"{}")}catch(_){return {}}}
const esc=v=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
function parseYouTube(input){try{const u=new URL(input);if(u.hostname==="youtu.be")return u.pathname.slice(1).split("/")[0];if(/(^|\.)youtube\.com$/.test(u.hostname)){if(u.pathname==="/watch")return u.searchParams.get("v");if(u.pathname.startsWith("/embed/"))return u.pathname.split("/")[2];}}catch(_){}return null}
function load(){if(!gameKey)return {};try{const x=JSON.parse(localStorage.getItem(STORE_PREFIX+gameKey)||"{}");return x&&typeof x==="object"&&!Array.isArray(x)?x:{};}catch(_){return {}}}
function save(x){if(!gameKey)throw new Error("Select a game before saving video.");localStorage.setItem(STORE_PREFIX+gameKey,JSON.stringify(x))}
function secs(v){const t=String(v??"").trim();if(!/^\d{1,3}:[0-5]\d$/.test(t))return null;const p=t.split(":").map(Number);return p[0]*60+p[1]}
function clockElapsed(period,clock){const q=Number(period),left=secs(clock),len=q<=4?600:300;if(!Number.isInteger(q)||q<1||left==null||left>len)return null;return (Math.min(q-1,4)*600+Math.max(0,q-5)*300)+(len-left)}
function videoForPbp(anchor,period,clock){
 if(!anchor||Number(anchor.period)!==Number(period))return null;
 const a=clockElapsed(anchor.period,anchor.clock),e=clockElapsed(period,clock),v=Number(anchor.videoSeconds);
 if(a==null||e==null||!Number.isFinite(v)||v<0||v+e-a<0)return null;
 return Math.round(v+e-a);
}
function ytAt(id,seconds){return "https://youtu.be/"+encodeURIComponent(id)+"?t="+Math.max(0,Math.round(seconds||0))+"s"}
function confidence(e){let n=25;if(e.tag&&e.tag!=="Other")n+=15;if(e.coverage)n+=15;if(e.ballHandler)n+=10;if(e.screener)n+=10;if((e.players||"").split(",").filter(Boolean).length>=5)n+=15;if(e.note)n+=5;if(e.source==="official-pbp")n+=5;return Math.min(100,n)}
function status(e){const n=confidence(e);return n>=85?"DETAILED TAG":n>=60?"PARTIAL TAG":"REVIEW"}
function classifyPbp(e){const d=String(e.description||e.action||"").toLowerCase();let tag="Other",points=null;if(/turnover|איבוד/.test(d))tag="Turnover";else if(/rebound|ריבאונד/.test(d))tag="Rebound";else if(/free throw|עונשין/.test(d))tag="Free Throw";else if(/3pt|3 pt|three point|שלוש/.test(d)){tag="Shot · 3PT";points=/made|makes|קלע/.test(d)?3:0}else if(/2pt|2 pt|layup|dunk|jumper|שתיים/.test(d)){tag="Shot · 2PT";points=/made|makes|קלע/.test(d)?2:0}else if(/foul|עבירה/.test(d))tag="Foul";return {tag,points}}
function importPbp(events){const s=load();if(!s.videoId)return {added:0,reason:"video"};const seen=new Set((s.events||[]).filter(x=>x.source==="official-pbp").map(x=>[x.period,x.gameClock,x.note].join("|")));let added=0;(events||[]).forEach(e=>{const key=[e.period,e.clock,e.description||e.action].join("|");if(seen.has(key))return;seen.add(key);const v=videoForPbp(s.anchors?.[e.period]||s.anchor,e.period,e.clock),a=classifyPbp(e);(s.events??=[]).push({time:v==null?"":Math.floor(v/60)+":"+String(v%60).padStart(2,"0"),period:e.period,gameClock:e.clock,tag:a.tag,note:e.description||e.action||"",kind:"evidence",points:a.points,offense:e.team||"",players:e.player||"",coverage:"",ballHandler:e.player||"",screener:"",source:"official-pbp",createdAt:new Date().toISOString()});added++});save(s);return {added}}
function assistFromEvidence(e){const text=((e.note||"")+" "+(e.tag||"")).toLowerCase();let coverage=e.coverage||"";if(!coverage){if(/switch/.test(text))coverage="Switch";else if(/drop/.test(text))coverage="Drop";else if(/trap|blitz/.test(text))coverage="Blitz / Trap";else if(/hedge|show/.test(text))coverage="Hedge / Show";else if(/ice|down/.test(text))coverage="ICE / Down";else if(/zone/.test(text))coverage="Zone"}return {...e,coverage,assistApplied:coverage!==e.coverage}}
function evidenceRows(s){return (s.events||[]).map(e=>{const estimated=e.source==="official-pbp",t=estimated?videoForPbp(s.anchors?.[e.period]||s.anchor,e.period,e.gameClock):secs(e.time);return {...e,videoSeconds:t,estimated,clipUrl:s.videoId&&t!=null?ytAt(s.videoId,t):null};});}
function filterEvidence(rows,f={}){return rows.filter(e=>(!f.offense||e.offense===f.offense)&&(!f.tag||e.tag===f.tag)&&(!f.source||e.source===f.source)&&(!f.kind||e.kind===f.kind)&&(!f.search||[e.note,e.players,e.ballHandler,e.screener,e.coverage,e.tag,e.gameClock,e.time,e.offense].filter(Boolean).join(" ").toLowerCase().includes(f.search.trim().toLowerCase())));}
const BACKUP_LIMIT=2*1024*1024;
function validateBackup(input,expectedGame=gameKey){
 if(typeof input==='string'&&input.length>BACKUP_LIMIT)throw new Error('Backup is too large (maximum 2 MB).');
 let b;try{b=typeof input==='string'?JSON.parse(input):input;}catch(_){throw new Error('Enter a valid JSON backup.');}
 const object=x=>x&&typeof x==='object'&&!Array.isArray(x);
 if(!object(b)||b.format!=='courtiq-video-backup'||b.version!==1)throw new Error('Unsupported CourtIQ video backup format.');
 if(!expectedGame||b.gameKey!==expectedGame)throw new Error('This backup belongs to a different game. Open that game before restoring.');
 const x=b.workspace;if(!object(x)||!(/^[A-Za-z0-9_-]{11}$/).test(x.videoId))throw new Error('Backup needs a valid YouTube video ID.');
 const out={videoId:x.videoId,url:ytAt(x.videoId,0),events:[],anchors:{}};
 const anchor=a=>{if(!object(a)||clockElapsed(a.period,a.clock)==null||typeof a.videoSeconds!=='number'||!Number.isFinite(a.videoSeconds)||a.videoSeconds<0||a.videoSeconds>59999)throw new Error('Invalid video sync anchor.');return {period:Number(a.period),clock:a.clock,videoSeconds:a.videoSeconds};};
 if(x.anchors!=null){if(!object(x.anchors))throw new Error('Invalid sync anchor map.');for(const [q,a] of Object.entries(x.anchors)){const v=anchor(a);if(String(v.period)!==q)throw new Error('Sync anchor period does not match its key.');out.anchors[q]=v;}}
 if(x.anchor!=null){out.anchor=anchor(x.anchor);if(!out.anchors[out.anchor.period])out.anchors[out.anchor.period]=out.anchor;}
 if(!Array.isArray(x.events)||x.events.length>10000)throw new Error('Backup events must be an array of at most 10,000 records.');
 const strings=['time','tag','note','offense','players','coverage','ballHandler','screener','createdAt','gameClock'];
 for(const [i,e] of x.events.entries()){
  if(!object(e)||!['evidence','possession'].includes(e.kind)||!['analyst-video','official-pbp'].includes(e.source))throw new Error('Invalid evidence record '+(i+1)+'.');
  const row={kind:e.kind,source:e.source};for(const k of strings){if(e[k]!=null){if(typeof e[k]!=='string'||e[k].length>10000)throw new Error('Invalid '+k+' in record '+(i+1)+'.');row[k]=e[k];}}
  if(e.source==='official-pbp'){if(e.kind!=='evidence')throw new Error('Imported PBP records must remain evidence only.');if(e.period!=null){if(!Number.isInteger(Number(e.period))||Number(e.period)<1)throw new Error('Invalid event period.');row.period=Number(e.period);}if(e.gameClock&&clockElapsed(e.period,e.gameClock)==null)throw new Error('Invalid PBP game clock.');}
  else if(secs(e.time)==null)throw new Error('Analyst record '+(i+1)+' needs a valid video timestamp.');
  if(e.points!=null&&(!Number.isInteger(e.points)||e.points<0||e.points>4))throw new Error('Invalid points in record '+(i+1)+'.');
  if(e.kind==='possession'&&e.points==null)throw new Error('Tagged possession needs a recorded point outcome.');row.points=e.points??null;out.events.push(row);
 }
 return {format:b.format,version:1,gameKey:expectedGame,gameLabel:typeof b.gameLabel==='string'?b.gameLabel.slice(0,500):'',workspace:out};
}
function backup(){const s=load();if(!s.videoId)throw new Error('Load a video before creating a backup.');const b={...validateBackup({format:'courtiq-video-backup',version:1,gameKey,gameLabel,workspace:s}),exportedAt:new Date().toISOString()};if(JSON.stringify(b,null,2).length>BACKUP_LIMIT)throw new Error('Backup exceeds the 2 MB transfer limit.');return b;}
function restoreBackup(input){const b=validateBackup(input);save(b.workspace);return b;}
function openRoom(){
 if(!gameKey)return;
 const filters={offense:"",tag:"",source:"",kind:"",search:""};
 const state=load(),modal=document.createElement("div");modal.className="modal cqVideoRoom";
 modal.innerHTML=`<div class="modalCard compareModal"><button class="modalX">×</button><small class="eyebrow">COURTIQ · VIDEO EVIDENCE ROOM</small><h2>Import Game Video</h2><p class="videoGameContext"><b>${esc(gameLabel)}</b><br>Video and tags are saved for this game in this browser.</p><p>Paste a YouTube game link. CourtIQ keeps video evidence separate from verified box-score facts: timestamps and tags are evidence; tactical conclusions require analyst review.</p><div class="importFields"><input id="videoUrl" placeholder="https://youtu.be/..." value="${esc(state.url||"")}"></div><div id="videoStatus" class="impStatus"></div><button id="loadVideo" class="runImport">LOAD VIDEO</button>${legacy().videoId&&!state.videoId?'<button id="attachLegacyVideo" class="importBtn">ASSIGN PREVIOUS UNLINKED VIDEO TO THIS GAME</button><p class="metricNote">Check the teams before assigning. The previous video remains preserved.</p>':""}<details class="videoBackup"><summary>Backup / restore video work</summary><p>Move this game's video tags and sync anchors between browsers using JSON. Restore replaces this game's video workspace only. Box-score data and lineup analytics are separate.</p><button id="createVideoBackup" class="importBtn">PREPARE BACKUP JSON</button><label>Backup JSON<textarea id="videoBackupJson" readonly placeholder="Prepare a backup, then select and copy this JSON into a file."></textarea></label><button id="selectVideoBackup" class="importBtn">SELECT BACKUP JSON</button><label>Paste a backup to restore<textarea id="videoRestoreJson" placeholder="Paste CourtIQ video backup JSON"></textarea></label><label>Or choose a JSON file<input id="videoBackupFile" type="file" accept=".json,application/json"></label><button id="previewVideoRestore" class="importBtn">PREVIEW RESTORE</button><p id="videoBackupStatus" role="status"></p><div id="videoRestorePreview" class="schema" hidden></div><button id="applyVideoRestore" class="runImport" hidden>REPLACE VIDEO WORKSPACE</button><button id="cancelVideoRestore" class="importBtn" hidden>CANCEL PREVIEW</button><button id="undoVideoRestore" class="importBtn" hidden>UNDO LAST RESTORE</button></details><div id="videoWorkspace"></div></div>`;
 document.body.appendChild(modal);modal.querySelector(".modalX").onclick=()=>modal.remove();modal.onclick=e=>{if(e.target===modal)modal.remove()};
 const attach=modal.querySelector("#attachLegacyVideo");if(attach)attach.onclick=()=>{save(legacy());modal.remove();openRoom();};
 const draw=()=>{const s=load(),box=modal.querySelector("#videoWorkspace");if(!s.videoId){box.innerHTML="";return}
 const events=(s.events||[]).map(e=>{if(e.source!=="official-pbp")return e;const t=videoForPbp(s.anchors?.[e.period]||s.anchor,e.period,e.gameClock);return {...e,time:t==null?"":Math.floor(t/60)+":"+String(t%60).padStart(2,"0")}}); const poss=events.filter(e=>e.kind==="possession"&&e.source!=="official-pbp"); const pts=poss.reduce((n,e)=>n+Number(e.points||0),0), ppp=poss.length?(pts/poss.length).toFixed(2):"—";
 const groups=Object.values(poss.reduce((m,e)=>{const k=(e.tag||"Other")+(e.coverage?" · vs "+e.coverage:"");(m[k]??={tag:k,rows:[],points:0});m[k].rows.push(e);m[k].points+=Number(e.points||0);return m},{})).sort((a,b)=>b.rows.length-a.rows.length);
 const tactical=groups.map(g=>({...g,ppp:g.rows.length?(g.points/g.rows.length).toFixed(2):"—",scoreRate:g.rows.length?Math.round(g.rows.filter(x=>Number(x.points)>0).length/g.rows.length*100):0,confidence:g.rows.length>=10?"STRONG SAMPLE":g.rows.length>=5?"DEVELOPING":"SMALL SAMPLE"}));
 box.innerHTML=`<div style="position:relative;padding-top:56.25%;margin:16px 0"><iframe id="cqVideo" style="position:absolute;inset:0;width:100%;height:100%;border:0;border-radius:12px" src="https://www.youtube.com/embed/${esc(s.videoId)}?enablejsapi=1" allow="accelerometer;autoplay;clipboard-write;encrypted-media;gyroscope;picture-in-picture" allowfullscreen></iframe></div>
 <div class="schema"><b>VIDEO LOADED · ${esc(s.videoId)}</b><br>Use the YouTube clock, enter a timestamp, then tag the possession. CourtIQ does not claim automatic computer-vision detection in this browser build.</div>
 <h3>Official PBP ↔ Video Sync</h3><div class="schema">Choose a visible game-clock moment and enter its YouTube timestamp. Links are estimated within that period only. Set a new anchor after each period or broadcast edit. Official events are evidence, not automatically counted as full possessions.</div><div class="importFields"><input id="anchorPeriod" type="number" min="1" max="8" placeholder="Period · 1"><input id="anchorClock" placeholder="Game clock · 09:42"><input id="anchorVideo" placeholder="Video time · 03:18"></div><button id="saveAnchor" class="importBtn">SAVE SYNC ANCHOR</button><div id="syncPreview"></div><div class="reportKpis"><div><small>TAGGED POSSESSIONS</small><b>${poss.length}</b></div><div><small>POINTS</small><b>${pts}</b></div><div><small>PPP</small><b>${ppp}</b></div><div><small>EVIDENCE</small><b>${events.length}</b></div></div><div class="importFields"><input id="evTime" placeholder="Timestamp · 12:34"><select id="evTag"><option>Pick & Roll</option><option>Transition</option><option>Turnover</option><option>Shot Quality</option><option>Offensive Rebound</option><option>Post Up</option><option>Isolation</option><option>ATO / Set Play</option><option>Defense</option><option>Other</option></select><select id="evResult"><option value="">Evidence only</option><option value="0">Possession · 0 pts</option><option value="1">Possession · 1 pt</option><option value="2">Possession · 2 pts</option><option value="3">Possession · 3 pts</option></select><input id="evOffense" placeholder="Offense · team"><select id="evCoverage"><option value="">Coverage · unknown</option><option>Drop</option><option>Switch</option><option>Hedge / Show</option><option>Blitz / Trap</option><option>ICE / Down</option><option>Under</option><option>Zone</option><option>Other</option></select><input id="evBallHandler" placeholder="Ball handler"><input id="evScreener" placeholder="Screener"><input id="evPlayers" placeholder="5-man lineup · comma separated"><input id="evNote" placeholder="Evidence note · what happened?"></div><button id="autoAssist" class="importBtn">AUTO ASSIST</button><button id="addEvidence" class="runImport">ADD VIDEO EVIDENCE</button>
 <h3>Tactical Findings · Evidence-backed</h3><div class="gameLibraryGrid">${tactical.length?tactical.map((g,gi)=>`<div class="card box"><small>${esc(g.confidence)}</small><h3>${esc(g.tag)}</h3><div class="reportKpis"><div><small>SAMPLE</small><b>${g.rows.length}</b></div><div><small>PPP</small><b>${g.ppp}</b></div><div><small>SCORE RATE</small><b>${g.scoreRate}%</b></div></div><button class="importBtn" data-evidence-group="${gi}">VIEW ${g.rows.length} EVIDENCE CLIPS</button><div data-evidence-list="${gi}" hidden class="videoList">${g.rows.map((e,i)=>{const t=secs(e.time);return `<div class="videoItem"><span>${i+1}</span><a href="${esc(ytAt(s.videoId,t))}" target="_blank" rel="noopener">${esc(e.time)} · ${esc(e.points)} pts</a> — ${esc(e.note||"Tagged possession")}</div>`}).join("")}</div></div>`).join(""):'<div class="schema">Tag possessions to generate tactical findings. CourtIQ will show sample size before any tactical interpretation.</div>'}</div><h3>Evidence Timeline</h3><div id="evidenceBrowser"></div>
 <div class="metricNote">Evidence status: analyst-tagged video. Link these timestamps to official Play-by-Play/box-score events before publishing tactical claims.</div>`;
 box.querySelector("#saveAnchor").onclick=()=>{const period=Number(box.querySelector("#anchorPeriod").value),clock=box.querySelector("#anchorClock").value.trim(),video=box.querySelector("#anchorVideo").value.trim(),vs=secs(video);if(clockElapsed(period,clock)==null||vs==null){modal.querySelector("#videoStatus").textContent="Enter period, game clock MM:SS and video time MM:SS.";return}const x=load();x.anchor={period,clock,videoSeconds:vs};(x.anchors??={})[period]=x.anchor;save(x);modal.querySelector("#videoStatus").textContent="PBP ↔ video anchor saved.";draw()};
 const preview=box.querySelector("#syncPreview"); if(s.anchor) preview.innerHTML='<div class="insight"><b>SYNC ACTIVE</b> · Q'+esc(s.anchor.period)+' '+esc(s.anchor.clock)+' = video '+Math.floor(s.anchor.videoSeconds/60)+':'+String(s.anchor.videoSeconds%60).padStart(2,"0")+'</div>';
 box.querySelector("#autoAssist").onclick=()=>{const tag=box.querySelector("#evTag").value,note=box.querySelector("#evNote").value.trim(),coverage=box.querySelector("#evCoverage").value;const a=assistFromEvidence({tag,note,coverage});if(a.coverage&&!coverage)box.querySelector("#evCoverage").value=a.coverage;modal.querySelector("#videoStatus").textContent=a.assistApplied?"Auto Assist suggested coverage from the analyst note. Review before saving.":"No safe additional inference found. Add PBP/roster evidence or review manually."};
 box.querySelector("#addEvidence").onclick=()=>{const time=box.querySelector("#evTime").value.trim(),tag=box.querySelector("#evTag").value,note=box.querySelector("#evNote").value.trim(),result=box.querySelector("#evResult").value,offense=box.querySelector("#evOffense").value.trim(),players=box.querySelector("#evPlayers").value.trim(),coverage=box.querySelector("#evCoverage").value,ballHandler=box.querySelector("#evBallHandler").value.trim(),screener=box.querySelector("#evScreener").value.trim();if(secs(time)==null){modal.querySelector("#videoStatus").textContent="Enter timestamp as MM:SS, for example 12:34.";return}const x=load();(x.events??=[]).push({time,tag,note,kind:result===""?"evidence":"possession",points:result===""?null:Number(result),offense,players,coverage,ballHandler,screener,source:"analyst-video",createdAt:new Date().toISOString()});save(x);modal.querySelector("#videoStatus").textContent="Video evidence saved locally.";draw()};
 box.querySelectorAll("[data-evidence-group]").forEach(b=>b.onclick=()=>{const el=box.querySelector('[data-evidence-list="'+b.dataset.evidenceGroup+'"]');el.hidden=!el.hidden});
 const browser=box.querySelector("#evidenceBrowser"),rows=evidenceRows(s);
 const options=(values,all)=>'<option value="">'+all+'</option>'+[...new Set(values.filter(Boolean))].sort().map(v=>'<option value="'+esc(v)+'">'+esc(v)+'</option>').join('');
 browser.innerHTML='<div class="pbpFilters"><label>Offense / team<select data-filter="offense">'+options(rows.map(e=>e.offense),'All teams')+'</select></label><label>Tag<select data-filter="tag">'+options(rows.map(e=>e.tag),'All tags')+'</select></label><label>Source<select data-filter="source"><option value="">All sources</option><option value="analyst-video">Analyst video</option><option value="official-pbp">Imported PBP</option></select></label><label>Record<select data-filter="kind"><option value="">All records</option><option value="evidence">Evidence only</option><option value="possession">Tagged possessions</option></select></label><label>Search<input data-filter="search" type="search" placeholder="Player, coverage or note"></label><button id="resetEvidenceFilters" class="importBtn">RESET FILTERS</button></div><p id="evidenceCount" role="status"></p><div id="filteredEvidence" class="videoList"></div>';
 const renderEvidence=()=>{const selected=filterEvidence(rows,filters);browser.querySelector('#evidenceCount').textContent=selected.length+' of '+rows.length+' records · '+selected.filter(e=>e.clipUrl).length+' video links. Findings above use all tagged possessions.';
 browser.querySelector('#filteredEvidence').innerHTML=selected.length?selected.map(e=>{const i=rows.indexOf(e);return '<div class="videoItem"><span>'+ (i+1)+'</span><div><b>'+esc(e.tag)+'</b> · '+esc(e.source==='official-pbp'?'Imported PBP':'Analyst video')+(e.kind==='possession'?' · '+esc(e.points)+' PTS':' · Evidence only')+(e.offense?' · '+esc(e.offense):'')+'<br>'+ (e.clipUrl?'<a href="'+esc(e.clipUrl)+'" target="_blank" rel="noopener">'+esc(Math.floor(e.videoSeconds/60)+':'+String(e.videoSeconds%60).padStart(2,'0'))+' · '+(e.estimated?'VIDEO · ESTIMATED':'OPEN VIDEO')+'</a>':'<b>VIDEO TIME UNKNOWN · SYNC REQUIRED</b>')+(e.gameClock?' · Q'+esc(e.period)+' '+esc(e.gameClock):'')+'<br>'+esc(e.note||'No note')+(e.players?'<br><small>Players: '+esc(e.players)+'</small>':'')+(e.coverage?'<br><small>Coverage: '+esc(e.coverage)+'</small>':'')+'<br><small>'+status(e)+' · '+confidence(e)+'% tag completeness</small></div><button data-del="'+i+'" class="importBtn" aria-label="Remove evidence record '+(i+1)+'">×</button></div>';}).join(''):'<div class="schema">'+(rows.length?'No evidence matches these filters. Reset or change the filters.':'No video evidence yet. Add a tag or import recorded PBP events.')+'</div>';
 browser.querySelectorAll('[data-del]').forEach(b=>b.onclick=()=>{const x=load();x.events.splice(Number(b.dataset.del),1);save(x);draw();});};
 browser.querySelectorAll('[data-filter]').forEach(field=>{field.value=filters[field.dataset.filter];field.oninput=()=>{filters[field.dataset.filter]=field.value;renderEvidence();};field.onchange=field.oninput;});
 browser.querySelector('#resetEvidenceFilters').onclick=()=>{Object.keys(filters).forEach(k=>filters[k]='');browser.querySelectorAll('[data-filter]').forEach(field=>field.value='');renderEvidence();};renderEvidence();
 };
 const backupStatus=modal.querySelector('#videoBackupStatus'),restoreInput=modal.querySelector('#videoRestoreJson'),preview=modal.querySelector('#videoRestorePreview'),apply=modal.querySelector('#applyVideoRestore'),cancel=modal.querySelector('#cancelVideoRestore'),undo=modal.querySelector('#undoVideoRestore');
 let staged=null,stagedSnapshot=null,previous=null,restored=null,fileRead=0;const roomGame=gameKey;
 const clearPreview=()=>{staged=null;preview.hidden=true;apply.hidden=true;cancel.hidden=true;};
 const prepare=()=>{try{const b=backup();modal.querySelector('#videoBackupJson').value=JSON.stringify(b,null,2);backupStatus.textContent='Backup ready: '+b.workspace.events.length+' records and '+Object.keys(b.workspace.anchors).length+' sync anchors. Select and copy the JSON into a file to keep it.';}catch(e){backupStatus.textContent=e.message;}};
 modal.querySelector('#createVideoBackup').onclick=prepare;
 modal.querySelector('#selectVideoBackup').onclick=()=>{const field=modal.querySelector('#videoBackupJson');if(!field.value){backupStatus.textContent='Prepare a backup first.';return;}field.focus();field.select();backupStatus.textContent='Backup JSON selected. Copy it and save it as a .json file.';};
 restoreInput.oninput=()=>{fileRead++;clearPreview();};
 modal.querySelector('#videoBackupFile').onchange=async e=>{const id=++fileRead,file=e.target.files?.[0];clearPreview();if(!file)return;if(file.size>BACKUP_LIMIT){backupStatus.textContent='Backup is too large (maximum 2 MB).';return;}try{const text=await file.text();if(id!==fileRead||roomGame!==gameKey||!modal.isConnected)return;restoreInput.value=text;backupStatus.textContent='File loaded. Preview it before replacing the workspace.';}catch(_){if(id===fileRead)backupStatus.textContent='Could not read the backup file.';}};
 modal.querySelector('#previewVideoRestore').onclick=()=>{clearPreview();try{staged=validateBackup(restoreInput.value);stagedSnapshot=JSON.stringify(load());const w=staged.workspace;preview.textContent='Game: '+gameLabel+' · Video: '+w.videoId+' · '+w.events.length+' records · '+w.events.filter(e=>e.kind==='possession').length+' tagged possessions · '+Object.keys(w.anchors).length+' sync anchors. Current workspace: '+(load().events||[]).length+' records. Review the video and teams before replacing. Imported PBP remains evidence only.';preview.hidden=false;apply.hidden=false;cancel.hidden=false;backupStatus.textContent='Preview only. No saved data has changed.';}catch(e){backupStatus.textContent=e.message;}};
 cancel.onclick=()=>{clearPreview();backupStatus.textContent='Preview cancelled. No saved data changed.';};
 apply.onclick=()=>{if(!staged||roomGame!==gameKey)return;try{const before=load();if(JSON.stringify(before)!==stagedSnapshot){clearPreview();backupStatus.textContent='Workspace changed since preview. Preview the backup again.';return;}restoreBackup(staged);previous=before;restored=JSON.stringify(load());clearPreview();undo.hidden=false;modal.querySelector('#videoUrl').value=load().url;backupStatus.textContent='Video workspace restored in this browser. Undo is available while this window stays open; prepare a backup to keep a copy.';draw();}catch(e){backupStatus.textContent=e.message;}};
 undo.onclick=()=>{if(previous==null||roomGame!==gameKey)return;try{if(JSON.stringify(load())!==restored){backupStatus.textContent='Workspace changed after restore. Prepare a backup before restoring another version.';return;}save(previous);previous=null;undo.hidden=true;modal.querySelector('#videoUrl').value=load().url||'';backupStatus.textContent='Previous video workspace restored.';draw();}catch(e){backupStatus.textContent=e.message;}};
 modal.querySelector("#loadVideo").onclick=()=>{const url=modal.querySelector("#videoUrl").value.trim(),id=parseYouTube(url);if(!id){modal.querySelector("#videoStatus").textContent="Paste a valid YouTube video URL.";return}const old=load();save({...old,url,videoId:id,events:old.videoId===id?(old.events||[]):[],anchor:old.videoId===id?old.anchor:null,anchors:old.videoId===id?(old.anchors||{}):{}});modal.querySelector("#videoStatus").textContent="Video connected to CourtIQ Video Room.";draw()};draw();
}
function install(){const bar=document.querySelector(".pills");if(bar&&!document.querySelector("#videoImport")){const b=document.createElement("button");b.id="videoImport";b.className="importBtn primaryAction";b.textContent="VIDEO IMPORT";b.onclick=openRoom;bar.appendChild(b)}
 document.querySelectorAll(".menu div").forEach(x=>{if(x.textContent.includes("Video Room")&&!x.dataset.videoBound){x.dataset.videoBound="1";x.addEventListener("click",openRoom)}})}
new MutationObserver(install).observe(document.documentElement,{childList:true,subtree:true});install();
window.CourtIQVideo={setGame,identity,open:openRoom,evidenceRows,filterEvidence,backup,validateBackup,restoreBackup,parseYouTube,importPbp,videoForPbp:(period,clock)=>{const s=load(),t=videoForPbp(s.anchors?.[period]||s.anchor,period,clock);return !s.videoId||t==null?null:{seconds:t,url:ytAt(s.videoId,t)}},state:load};
setGame(window.CourtIQActiveGame);
})();