import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "npm:@supabase/supabase-js@2";
import * as cheerio from "npm:cheerio@1.0.0";

const cors={"Access-Control-Allow-Origin":"https://ofirdad12.github.io","Access-Control-Allow-Headers":"authorization, apikey, content-type","Access-Control-Allow-Methods":"POST, OPTIONS","Content-Type":"application/json","Cache-Control":"no-store"};
const j=(body:unknown,status=200)=>new Response(JSON.stringify(body),{status,headers:cors});
const clean=(v:any)=>String(v??"").replace(/\s+/g," ").trim();
const n=(v:any)=>{const m=clean(v).replaceAll(",","").match(/-?\d+/);return m?Number(m[0]):0;};
const ma=(v:any)=>{const m=clean(v).match(/(\d+)\s*[-/–—]\s*(\d+)/);return m?[Number(m[1]),Number(m[2])]:[0,0];};
const pct=(a:number,b:number)=>b>0?Math.round(a/b*1000)/10:null;
const r1=(x:number)=>Math.round(x*10)/10;
const minutes=(v:any)=>{const s=clean(v),m=s.match(/^(\d+):(\d{2})$/);return m?r1(Number(m[1])+Number(m[2])/60):(Number.isFinite(Number(s))?r1(Number(s)):0);};
const tableRows=($:cheerio.CheerioAPI,t:any)=>$(t).find("tr").toArray().map((tr:any)=>$(tr).find("th,td").toArray().map((c:any)=>clean($(c).text()))).filter((r:string[])=>r.some(Boolean));

function validateUrl(raw:string){
 const u=new URL(raw);if(u.protocol!=="https:")throw new Error("Use an HTTPS official game URL.");
 const ibba=/^(www\.)?ibasketball\.co\.il$/.test(u.hostname),genius=/^(?:fiba)?livestats\.dcd\.shared\.geniussports\.com$/.test(u.hostname),plk=/^(www\.)?plk\.pl$/.test(u.hostname),euro=/^(www\.)?euroleaguebasketball\.net$/.test(u.hostname);
 if(ibba&&!/^\/match\/[a-z0-9]+(?:-[a-z0-9]+)*\/?$/i.test(u.pathname))throw new Error("Use an official IBBA /match/... URL.");
 if(genius&&!/^\/u\/[a-z0-9_-]+\/\d+\/(?:index\.html|p\.html|pbp\.html|bs\.html)?$/i.test(u.pathname))throw new Error("Use an official FIBA LiveStats / Genius Sports game URL.");
 if(plk&&!/^\/mecz\/\d+(?:\/[^?#]*)?\/?$/i.test(u.pathname))throw new Error("Use an official plk.pl/mecz/... URL.");
 if(euro&&!/^\/en\/eurocup\/game-center\/\d{4}-\d{2}\/[a-z0-9-]+\/U\d{4}\/\d+\/?$/i.test(u.pathname))throw new Error("Use an official EuroCup game-center URL.");
 if(!ibba&&!genius&&!plk&&!euro)throw new Error("Live Bench supports IBBA, FIBA LiveStats / Genius Sports, EuroCup and ORLEN Basket Liga (PLK).");
 return {u,provider:genius?"GENIUS_LIVESTATS":plk?"PLK":euro?"EUROCUP":"IBBA"};
}
function calc(t:any,o:any){const fga=t.two_pa+t.three_pa,fgm=t.two_pm+t.three_pm,ofga=o.two_pa+o.three_pa,poss=fga+.44*t.fta-t.oreb+t.tov,oposs=ofga+.44*o.fta-o.oreb+o.tov;return {possessions:r1(poss),efg:pct(fgm+.5*t.three_pm,fga),ts:pct(t.points,2*(fga+.44*t.fta)),three_pa_rate:pct(t.three_pa,fga),tov_pct:pct(t.tov,fga+.44*t.fta+t.tov),orb_pct:pct(t.oreb,t.oreb+o.dreb),ftr:pct(t.fta,fga),ortg:poss>0?r1(t.points/poss*100):null,drtg:oposs>0?r1(o.points/oposs*100):null};}
function validateSide(t:any,label:string){for(const k of ["points","two_pm","two_pa","three_pm","three_pa","ftm","fta","oreb","dreb","tov","ast"])if(!Number.isFinite(Number(t[k]))||Number(t[k])<0)throw new Error(label+" has invalid "+k+".");if(t.two_pm>t.two_pa||t.three_pm>t.three_pa||t.ftm>t.fta)throw new Error(label+" has makes greater than attempts.");const shots=2*t.two_pm+3*t.three_pm+t.ftm;if(shots!==t.points)throw new Error(label+" live totals are temporarily inconsistent. Keeping the previous valid snapshot.");}
function advancedPlayer(p:any){const fga=p.two_pa+p.three_pa,fgm=p.two_pm+p.three_pm;return {...p,fgm,fga,rebounds:p.oreb+p.dreb,efg:pct(fgm+.5*p.three_pm,fga),ts:pct(p.points,2*(fga+.44*p.fta))};}
function leaders(players:any[]){const played=players.filter(p=>p.minutes>0||p.points>0),top=(k:string)=>[...played].sort((a,b)=>Number(b[k]||0)-Number(a[k]||0))[0];if(!played.length)return[];const a=top("points"),b=top("rebounds"),c=top("ast");return [[a.name,a.points,"PTS"],[b.name,b.rebounds,"REB"],[c.name,c.ast,"AST"]];}
function clockSeconds(v:any){const m=String(v||"").match(/(\d+):(\d{2})/);return m?Number(m[1])*60+Number(m[2]):99999;}
function quartersFromPbp(events:any[]){const map=new Map<number,any>();for(const e of events){const s=String(e.score||"").match(/(\d+)\s*[-:]\s*(\d+)/),sec=clockSeconds(e.clock);if(!e.period||!s||sec===99999)continue;const old=map.get(e.period);if(!old||sec<old.sec)map.set(e.period,{sec,h:Number(s[1]),a:Number(s[2])});}let h=0,a=0;return [...map.entries()].sort((x,y)=>x[0]-y[0]).map(([,x])=>{const q=[Math.max(0,x.h-h),Math.max(0,x.a-a)];h=x.h;a=x.a;return q;});}

function ibbaTeamTotal($:cheerio.CheerioAPI,table:any){const rows=tableRows($,table),hi=rows.findIndex(r=>{const x=r.join(" | ");return x.includes("2 נק")&&x.includes("3 נק")&&x.includes("מהקו");});if(hi<0)throw new Error("IBBA live box-score header was not found.");const h=rows[hi],total=rows.find(r=>r.some(c=>/^(?:סך\s*הכל|סה["׳']?כ)$/i.test(clean(c))));if(!total)throw new Error("IBBA live team total was not found.");const col=(...x:string[])=>{const i=h.findIndex(v=>x.some(k=>clean(v).includes(k)));if(i<0)throw new Error("IBBA live box score is missing "+x[0]+".");return i;};const [two_pm,two_pa]=ma(total[col("2 נק")]),[three_pm,three_pa]=ma(total[col("3 נק")]),[ftm,fta]=ma(total[col("מהקו")]);return {points:n(total[col("נק'","נק׳")]),two_pm,two_pa,three_pm,three_pa,ftm,fta,oreb:n(total[col("ריב׳ הת׳","ריב' הת'","ריב הת")]),dreb:n(total[col("ריב׳ הג׳","ריב' הג'","ריב הג")]),tov:n(total[col("איב'","איב׳","איב")]),ast:n(total[col("אס'","אס׳","אס")])};}
function ibbaPlayers($:cheerio.CheerioAPI,table:any){const out=$(table).find("tbody tr, tr").toArray().filter((tr:any)=>$(tr).find("td[data-key]").length).map((tr:any)=>{const v=(k:string)=>clean($(tr).find(`[data-key="${k}"]`).text()),[two_pm,two_pa]=ma(v("fgs")),[three_pm,three_pa]=ma(v("threeps")),[ftm,fta]=ma(v("fts"));return advancedPlayer({name:clean($(tr).find(".data-name").text()),number:n($(tr).find(".data-number").text()),starter:$(tr).hasClass("lineup"),minutes:minutes(v("min")),points:n(v("pts")),two_pm,two_pa,three_pm,three_pa,ftm,fta,dreb:n(v("def")),oreb:n(v("off")),steals:n(v("stl")),tov:n(v("to")),ast:n(v("ast")),blocks:n(v("blk"))});});if(!out.length)throw new Error("IBBA live player rows were not found.");return out;}
function ibbaPbp($:cheerio.CheerioAPI,home:string,away:string){const seen=new Set<string>(),out:any[]=[];$("[data-event-timeline] .sp-vertical-timeline-minute").each((order:number,el:any)=>{const node=$(el),cl=String(node.attr("class")||""),side=cl.includes("timeline-minute-home")?"home":cl.includes("timeline-minute-away")?"away":"",p=Number(cl.match(/(?:^|\s)quarter-(\d+)(?:\s|$)/)?.[1]||clean(node.find(".minute .quarter").first().text()).match(/\d+/)?.[0]||0),clock=clean(node.find(".minute .time").first().text()),score=clean(node.find(".minute .score").first().text()),action=node.find(".action").first(),player=clean(action.find("a").first().text()),description=clean(action.find(".description").first().text())||clean(action.text()),type=cl.match(/(?:^|\s)key-([^\s]+)/)?.[1]||"event";if(!p&&!clock&&!description)return;const key=[p,clock,score,side,player,description,type].join("|");if(seen.has(key))return;seen.add(key);out.push({period:p,period_label:"Q"+p,clock,score,side,team:side==="home"?home:side==="away"?away:"",player,description,type,_order:order});});out.sort((a,b)=>a.period-b.period||clockSeconds(b.clock)-clockSeconds(a.clock)||a._order-b._order);return out.map(({_order,...x})=>x);}
function ibbaNames($:cheerio.CheerioAPI){const names:string[]=[];$("a[href*='/team/']").each((_:number,a:any)=>{const x=clean($(a).text());if(x&&x.length>1&&!names.includes(x))names.push(x);});if(names.length>=2)return names.slice(0,2);const title=clean($("title").text()).replace(/\s*-\s*IBBA.*$/i,"").split(/\s+[—–]\s+/).map(clean).filter(Boolean);return [title[0]||"Home",title[1]||"Away"];}

function geniusTeam(team:any){const players=Object.entries(team?.pl||{}).map(([key,row]:any)=>{const mins=minutes(row?.sMinutes||"0:00"),name=clean([row?.firstName||row?.internationalFirstName,row?.familyName||row?.internationalFamilyName].filter(Boolean).join(" "))||clean(row?.name)||"Player "+key;return advancedPlayer({id:String(row?.personId||key),number:n(row?.shirtNumber||row?.jerseyNumber),name,starter:Number(row?.starter||row?.isStarter||0)===1||row?.starter===true||row?.isStarter===true,minutes:mins,points:Number(row?.sPoints||0),two_pm:Number(row?.sTwoPointersMade||0),two_pa:Number(row?.sTwoPointersAttempted||0),three_pm:Number(row?.sThreePointersMade||0),three_pa:Number(row?.sThreePointersAttempted||0),ftm:Number(row?.sFreeThrowsMade||0),fta:Number(row?.sFreeThrowsAttempted||0),dreb:Number(row?.sReboundsDefensive||0),oreb:Number(row?.sReboundsOffensive||0),steals:Number(row?.sSteals||0),tov:Number(row?.sTurnovers||0),ast:Number(row?.sAssists||0),blocks:Number(row?.sBlocks||0)});});const total={points:Number(team?.tot_sPoints??team?.score??0),two_pm:Number(team?.tot_sTwoPointersMade||0),two_pa:Number(team?.tot_sTwoPointersAttempted||0),three_pm:Number(team?.tot_sThreePointersMade||0),three_pa:Number(team?.tot_sThreePointersAttempted||0),ftm:Number(team?.tot_sFreeThrowsMade||0),fta:Number(team?.tot_sFreeThrowsAttempted||0),oreb:Number(team?.tot_sReboundsOffensive||0),dreb:Number(team?.tot_sReboundsDefensive||0),tov:Number(team?.tot_sTurnovers||0),ast:Number(team?.tot_sAssists||0)};return {total,players};}
function geniusPbp(data:any,home:string,away:string){const rosters=[data?.tm?.["1"]?.pl||{},data?.tm?.["2"]?.pl||{}],pname=(team:number,pno:any)=>{const r=rosters[team-1]?.[String(pno)]||{};return clean([r.firstName||r.internationalFirstName,r.familyName||r.internationalFamilyName].filter(Boolean).join(" "));};return (Array.isArray(data?.pbp)?data.pbp:[]).map((e:any,i:number)=>{const t=Number(e?.tno??e?.teamNumber??0),raw=Number(e?.period??e?.per??0),ot=String(e?.periodType||e?.perType||"").toUpperCase()==="OVERTIME",period=ot?4+Math.max(1,raw):raw,action=clean(e?.actionType||e?.action||e?.type||"event"),sub=clean(e?.subType||e?.subtype||""),s1=e?.s1??e?.score1??"",s2=e?.s2??e?.score2??"";return {period,period_label:ot?"OT"+Math.max(1,raw):"Q"+period,clock:String(e?.gt||e?.clock||""),score:(s1!==""||s2!=="")?String(s1||0)+"-"+String(s2||0):"",side:t===1?"home":t===2?"away":"",team:t===1?home:t===2?away:"",player:clean(e?.player)||pname(t,e?.pno),description:clean([action,sub].filter(Boolean).join(" · ")),type:action||"event",subtype:sub||null,success:e?.success??null,x:e?.x??null,y:e?.y??null,action_number:e?.actionNumber??e?.actionNo??i+1};}).filter((e:any)=>e.period||e.clock||e.description);}
function geniusQuarters(data:any,events:any[]){const h=data?.tm?.["1"]||{},a=data?.tm?.["2"]||{},out:any[]=[];for(let i=1;i<=12;i++){const k="p"+i+"_score";if(h[k]!=null||a[k]!=null)out.push([Number(h[k]||0),Number(a[k]||0)]);}return out.length?out:quartersFromPbp(events);}

function plkPlayerData($:cheerio.CheerioAPI,table:any){const rows=tableRows($,table).filter(r=>r.length),totalRow=rows.find(r=>clean(r[0]||"").toLowerCase()==="suma");if(!totalRow||totalRow.length<22)throw new Error("PLK team total row was not found.");const [two_pm,two_pa]=ma(totalRow[3]),[three_pm,three_pa]=ma(totalRow[5]),[ftm,fta]=ma(totalRow[9]);const total={points:n(totalRow[1]),two_pm,two_pa,three_pm,three_pa,ftm,fta,oreb:n(totalRow[11]),dreb:n(totalRow[12]),tov:n(totalRow[18]),ast:n(totalRow[14])};const players=rows.map(r=>{const label=clean(r[0]||"");let cut=0;while(cut<label.length&&/\d/.test(label[cut]))cut++;const numberText=label.slice(0,cut),name=label.slice(cut).trim(),minuteText=clean(r[2]||"");if(!numberText||!name||!/^\d{1,3}:\d{2}$/.test(minuteText))return null;const [p2m,p2a]=String(r[3]||"").includes("/")?ma(r[3]):[0,0],[p3m,p3a]=String(r[5]||"").includes("/")?ma(r[5]):[0,0],[fm,fa]=String(r[9]||"").includes("/")?ma(r[9]):[0,0];return advancedPlayer({number:Number(numberText),name,starter:false,minutes:minutes(minuteText),points:n(r[1]),two_pm:p2m,two_pa:p2a,three_pm:p3m,three_pa:p3a,ftm:fm,fta:fa,oreb:n(r[11]),dreb:n(r[12]),ast:n(r[14]),steals:n(r[17]),tov:n(r[18]),blocks:n(r[19])});}).filter(Boolean);if(!players.length)throw new Error("PLK player rows were not found.");return {total,players};}
function plkNames($:cheerio.CheerioAPI){const title=clean($("title").text()),m=title.match(/^(.+?)\s+vs\s+(.+?)\s*\|/i);if(!m)throw new Error("Could not identify PLK teams.");return [clean(m[1]),clean(m[2])];}
function plkType(description:string){const d=description.toLowerCase();if(/rzut woln|osobist/.test(d))return"free_throw";if(/strata/.test(d))return"turnover";if(/zbiórka|zbiorka/.test(d))return"rebound";if(/asysta/.test(d))return"assist";if(/przechwyt/.test(d))return"steal";if(/blok/.test(d))return"block";if(/faul/.test(d))return"foul";if(/zmiana|wejście|wejscie|zejście|zejscie/.test(d))return"substitution";if(/celny|niecelny|lay-up|alley-oop|z wyskoku|za [23]/.test(d))return"shot";return"other";}
function plkPbp($:cheerio.CheerioAPI,home:string,away:string){const raw:any[]=[];$("body *").each((order:number,el:any)=>{const node=$(el),text=clean(node.text());if(text.length<8||text.length>260)return;const m=text.match(/^(\d{1,3}):(\d{1,3})\s+(\d{2}):(\d{2}):(\d{2})\s+(.+)$/);if(!m)return;const childMatch=node.children().toArray().some((c:any)=>/^\d{1,3}:\d{1,3}\s+\d{2}:\d{2}:\d{2}\s+/.test(clean($(c).text())));if(childMatch)return;const description=clean(m[6]),imageLabels=node.find("img").toArray().map((img:any)=>clean($(img).attr("alt")||$(img).attr("title")||"")).filter(Boolean),teamLabel=imageLabels.find((x:string)=>x===home||x===away)||"";raw.push({order,score:m[1]+"-"+m[2],clock:m[3]+":"+m[4],description,teamLabel});});const seen=new Set<string>(),out:any[]=[],verb="celny|niecelny|strata|zbiórka|zbiorka|asysta|faul|przechwyt|blok|zmiana|wygrany|przegrany";let period=1,starts=0;for(const row of raw.sort((a,b)=>a.order-b.order)){if(/start części gry/i.test(row.description)){starts++;period=Math.max(1,starts);}const key=[period,row.clock,row.score,row.description,row.teamLabel].join("|");if(seen.has(key))continue;seen.add(key);const side=row.teamLabel===home?"home":row.teamLabel===away?"away":"",pm=row.description.match(new RegExp("^\\d+,\\s*(.+?)\\s+(?="+verb+")","i"));out.push({period,period_label:period<=4?"Q"+period:"OT"+(period-4),clock:row.clock,score:row.score,side,team:row.teamLabel,player:pm?clean(pm[1]):"",description:row.description,type:plkType(row.description)});}return out;}

function elNum(o:any,...keys:string[]){for(const k of keys)if(o?.[k]!==undefined&&o?.[k]!==null&&o?.[k]!=="")return Number(o[k])||0;return 0;}
function eurocupSide(side:any){const t=side?.total||{},players=(side?.players||[]).map((row:any)=>{const s=row?.stats||{},p=row?.player||{},person=p?.person||{},min=elNum(s,"timePlayed")/60;return advancedPlayer({id:String(person?.code||person?.id||""),number:Number(p?.dorsal||0),name:clean(person?.name||person?.displayName||[person?.firstName,person?.lastName].filter(Boolean).join(" ")||""),starter:Boolean(s?.startFive??s?.isStarter??s?.starter??false),minutes:r1(min),points:elNum(s,"points"),two_pm:elNum(s,"fieldGoalsMade2","twoPointersMade"),two_pa:elNum(s,"fieldGoalsAttempted2","twoPointersAttempted"),three_pm:elNum(s,"fieldGoalsMade3","threePointersMade"),three_pa:elNum(s,"fieldGoalsAttempted3","threePointersAttempted"),ftm:elNum(s,"freeThrowsMade"),fta:elNum(s,"freeThrowsAttempted"),oreb:elNum(s,"offensiveRebounds"),dreb:elNum(s,"defensiveRebounds"),tov:elNum(s,"turnovers"),ast:elNum(s,"assistances","assists"),steals:elNum(s,"steals"),blocks:elNum(s,"blocksFavour","blocks")});});const three_pm=elNum(t,"fieldGoalsMade3","threePointersMade"),three_pa=elNum(t,"fieldGoalsAttempted3","threePointersAttempted"),fgm=elNum(t,"fieldGoalsMade","fieldGoalsMadeTotal")||elNum(t,"fieldGoalsMade2","twoPointersMade")+three_pm,fga=elNum(t,"fieldGoalsAttempted","fieldGoalsAttemptedTotal")||elNum(t,"fieldGoalsAttempted2","twoPointersAttempted")+three_pa;return {total:{points:elNum(t,"points"),two_pm:elNum(t,"fieldGoalsMade2","twoPointersMade")||(fgm-three_pm),two_pa:elNum(t,"fieldGoalsAttempted2","twoPointersAttempted")||(fga-three_pa),three_pm,three_pa,ftm:elNum(t,"freeThrowsMade"),fta:elNum(t,"freeThrowsAttempted"),oreb:elNum(t,"offensiveRebounds"),dreb:elNum(t,"defensiveRebounds"),tov:elNum(t,"turnovers"),ast:elNum(t,"assistances","assists")},players};}
function eurocupPbp(data:any,home:string,away:string){const codeA=clean(data?.CodeTeamA||data?.codeTeamA||""),codeB=clean(data?.CodeTeamB||data?.codeTeamB||""),blocks=[data?.FirstQuarter,data?.SecondQuarter,data?.ThirdQuarter,data?.ForthQuarter,...(Array.isArray(data?.ExtraTime)?data.ExtraTime:[data?.ExtraTime])],out:any[]=[];blocks.forEach((block:any,bi:number)=>{const period=bi<4?bi+1:5+Math.max(0,bi-4),rows=Array.isArray(block)?block:Array.isArray(block?.Rows)?block.Rows:Array.isArray(block?.plays)?block.plays:[];for(const e of rows){const code=clean(e?.CODETEAM||e?.CodeTeam||e?.TEAM||""),side=code&&code===codeA?"home":code&&code===codeB?"away":"",mark=clean(e?.MARKERTIME||e?.MarkerTime||""),clock=/^\d{1,2}:\d{2}$/.test(mark)?mark:"",a=e?.POINTS_A??e?.PointsA,b=e?.POINTS_B??e?.PointsB,score=a!=null&&b!=null?String(a)+"-"+String(b):"",description=clean(e?.PLAYINFO||e?.PlayInfo||e?.COMMENT||e?.Comment||e?.PLAYTYPE||"event");out.push({period,period_label:period<=4?"Q"+period:"OT"+(period-4),clock,score,side,team:side==="home"?home:side==="away"?away:"",player:clean(e?.PLAYER||e?.Player||""),description,type:clean(e?.PLAYTYPE||e?.PlayType||"event"),action_number:Number(e?.NUMBEROFPLAY??e?.NumberOfPlay??out.length+1)});}});return out.sort((a,b)=>Number(a.action_number)-Number(b.action_number));}

function buildUi(provider:string,url:string,homeName:string,awayName:string,home:any,away:any,players:any,quarters:any[],playByPlay:any[]){validateSide(home,homeName);validateSide(away,awayName);const hm=calc(home,away),am=calc(away,home),latest=[...playByPlay].filter(e=>e.period&&e.clock).sort((a,b)=>b.period-a.period||clockSeconds(a.clock)-clockSeconds(b.clock))[0]||null,factor=(label:string,a:any,b:any)=>[label,a??0,b??0],providerLabel=provider==="PLK"?"ORLEN BASKET LIGA / PLK":provider==="EUROCUP"?"EUROCUP · EUROLEAGUE BASKETBALL":provider==="IBBA"?"IBBA":"FIBA LIVESTATS / GENIUS SPORTS",comp=provider==="PLK"?"ORLEN Basket Liga · Poland":provider==="EUROCUP"?"EuroCup":provider==="IBBA"?"IBBA Live":"FIBA LiveStats";return {id:"LIVE",comp,date:"LIVE",home:homeName,away:awayName,hs:home.points,as:away.points,quarters,sourceUrl:url,sourceLabel:providerLabel+" · LIVE PREVIEW · NOT SAVED",confidence:"LIVE PREVIEW · NOT FINAL",livePreview:true,raw:{home,away},calculated:{home:hm,away:am},factors:[factor("eFG%",hm.efg,am.efg),factor("TOV%",hm.tov_pct,am.tov_pct),factor("ORB%",hm.orb_pct,am.orb_pct),factor("FTr",hm.ftr,am.ftr)],stats:[["Points",home.points,away.points],["2P",home.two_pm+"/"+home.two_pa,away.two_pm+"/"+away.two_pa],["3P",home.three_pm+"/"+home.three_pa,away.three_pm+"/"+away.three_pa],["FT",home.ftm+"/"+home.fta,away.ftm+"/"+away.fta],["Assists",home.ast,away.ast],["Turnovers",home.tov,away.tov],["Offensive Rebounds",home.oreb,away.oreb]],metrics:[["eFG%",hm.efg==null?"—":hm.efg+"%",am.efg==null?"—":am.efg+"%"],["TOV%",hm.tov_pct==null?"—":hm.tov_pct+"%",am.tov_pct==null?"—":am.tov_pct+"%"],["ORB%",hm.orb_pct==null?"—":hm.orb_pct+"%",am.orb_pct==null?"—":am.orb_pct+"%"]],players:{home:players[0],away:players[1]},leaders:leaders(players[0]),awayLeaders:leaders(players[1]),playByPlay,playByPlayStatus:playByPlay.length?"published":"not_published",live:{provider,latest_event:latest,event_count:playByPlay.length,refreshed_at:new Date().toISOString(),quality:"VALID_SNAPSHOT"}};}

Deno.serve(async(req:Request)=>{if(req.method==="OPTIONS")return new Response(null,{headers:cors});if(req.method!=="POST")return j({error:"Method not allowed"},405);try{const auth=req.headers.get("Authorization");if(!auth)return j({error:"Sign in is required."},401);const supabaseUrl=Deno.env.get("SUPABASE_URL")!,anon=Deno.env.get("SUPABASE_ANON_KEY")!,userDb=createClient(supabaseUrl,anon,{global:{headers:{Authorization:auth}}}),{data:clubs,error:clubErr}=await userDb.from("clubs").select("id").eq("slug","maccabi-bnot-ashdod").limit(1);if(clubErr)throw clubErr;if(!clubs?.length)return j({error:"This account does not have access to the CourtIQ pilot."},403);const body=await req.json(),{u,provider}=validateUrl(String(body?.url||"")),browserHeaders={"User-Agent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 Chrome/140 Safari/537.36","Accept":"text/html,application/xhtml+xml,application/json;q=0.9,*/*;q=0.8","Cache-Control":"no-cache","Pragma":"no-cache"};let ui:any;
 if(provider==="GENIUS_LIVESTATS"){const m=u.pathname.match(/^\/u\/([^/]+)\/(\d+)\//i);if(!m)throw new Error("Could not read Genius game ID.");const gameId=m[2],res=await fetch(`${u.protocol}//${u.host}/data/${gameId}/data.json`,{headers:{...browserHeaders,"Accept":"application/json","X-Requested-With":"XMLHttpRequest","Referer":u.toString()}});if(!res.ok)throw new Error("LiveStats returned HTTP "+res.status);const data=await res.json(),ht=data?.tm?.["1"],at=data?.tm?.["2"];if(!ht||!at)throw new Error("LiveStats does not contain both teams yet.");const home=clean(ht.name||ht.nameInternational||ht.shortName),away=clean(at.name||at.nameInternational||at.shortName),hp=geniusTeam(ht),ap=geniusTeam(at),pbp=geniusPbp(data,home,away);ui=buildUi(provider,u.toString(),home,away,hp.total,ap.total,[hp.players,ap.players],geniusQuarters(data,pbp),pbp);
 }else if(provider==="IBBA"){const res=await fetch(u.toString(),{headers:browserHeaders});if(!res.ok)throw new Error("IBBA returned HTTP "+res.status);const html=await res.text(),$=cheerio.load(html),tables:any[]=[];$("table").each((_:number,t:any)=>{const h=tableRows($,t).slice(0,8).flat().join(" | ");if(h.includes("2 נק")&&h.includes("3 נק")&&h.includes("איב")&&h.includes("אס"))tables.push(t);});if(tables.length<2)throw new Error("IBBA has not published both live box-score tables yet.");const [home,away]=ibbaNames($),ht=ibbaTeamTotal($,tables[0]),at=ibbaTeamTotal($,tables[1]),players=[ibbaPlayers($,tables[0]),ibbaPlayers($,tables[1])],pbp=ibbaPbp($,home,away);ui=buildUi(provider,u.toString(),home,away,ht,at,players,quartersFromPbp(pbp),pbp);
 }else if(provider==="PLK"){const base=new URL(u.toString());base.search="";base.hash="";base.pathname=base.pathname.replace(/\/$/,"").replace(/\/(?:statystyki|akcja-po-akcji)$/i,"");const statsUrl=new URL(base.toString());statsUrl.pathname+="/statystyki";const pbpUrl=new URL(base.toString());pbpUrl.pathname+="/akcja-po-akcji";const [sr,pr]=await Promise.all([fetch(statsUrl.toString(),{headers:browserHeaders}),fetch(pbpUrl.toString(),{headers:browserHeaders})]);if(!sr.ok)throw new Error("PLK statistics returned HTTP "+sr.status);const sh=await sr.text(),$s=cheerio.load(sh),tables:any[]=[];$s("table").each((_:number,t:any)=>{const rows=tableRows($s,t),sum=rows.find(r=>clean(r[0]||"").toLowerCase()==="suma");if(sum&&sum.length>=22&&clean(sum[3]||"").includes("/"))tables.push(t);});if(tables.length<2)throw new Error("PLK has not published both live box-score tables yet.");const [home,away]=plkNames($s),hp=plkPlayerData($s,tables[0]),ap=plkPlayerData($s,tables[1]);let pbp:any[]=[];if(pr.ok){const ph=await pr.text();pbp=plkPbp(cheerio.load(ph),home,away);}ui=buildUi(provider,u.toString(),home,away,hp.total,ap.total,[hp.players,ap.players],quartersFromPbp(pbp),pbp);
 }else{const m=u.pathname.match(/\/U(\d{4})\/(\d+)\/?$/i);if(!m)throw new Error("Could not read EuroCup season/game code.");const season="U"+m[1],gameCode=m[2],h={"Accept":"application/json"},[sr,gr,pr]=await Promise.all([fetch(`https://api-live.euroleague.net/v2/competitions/U/seasons/${season}/games/${gameCode}/stats`,{headers:h}),fetch(`https://api-live.euroleague.net/v2/competitions/U/seasons/${season}/games/${gameCode}`,{headers:h}),fetch(`https://live.euroleague.net/api/PlayByPlay?gamecode=${encodeURIComponent(gameCode)}&seasoncode=${encodeURIComponent(season)}`,{headers:h})]);if(!sr.ok)throw new Error("EuroCup stats returned HTTP "+sr.status);if(!gr.ok)throw new Error("EuroCup game header returned HTTP "+gr.status);const stats=await sr.json(),game=await gr.json(),local=stats?.local,road=stats?.road;if(!local||!road)throw new Error("EuroCup live box score is not published yet.");const home=clean(game?.local?.club?.name||game?.local?.club?.abbreviatedName||local?.team?.name||""),away=clean(game?.road?.club?.name||game?.road?.club?.abbreviatedName||road?.team?.name||"");if(!home||!away)throw new Error("Could not identify EuroCup teams.");const hp=eurocupSide(local),ap=eurocupSide(road),hs=game?.local?.score?.byQuarter||[],as=game?.road?.score?.byQuarter||[],quarters=Array.isArray(hs)&&Array.isArray(as)?hs.map((v:any,i:number)=>[Number(v||0),Number(as[i]||0)]):[];let pbp:any[]=[];if(pr.ok){try{pbp=eurocupPbp(await pr.json(),home,away);}catch(_){pbp=[];}}ui=buildUi(provider,u.toString(),home,away,hp.total,ap.total,[hp.players,ap.players],quarters,pbp);
 }
 return j({preview:true,saved:false,ui,refreshed_at:new Date().toISOString()});}catch(e){return j({error:e instanceof Error?e.message:String(e)},422);}});
