const assert=require('node:assert/strict');global.CourtIQDecisionLab=require('../decision-lab');global.CourtIQPlayerScan=require('../player-scan');global.CourtIQSeasonWorkbench=require('../season-workbench');global.CourtIQLineupEngine=require('../lineup-engine');global.CourtIQCourtAnalytics=require('../court-analytics');const api=require('../tactical-workspace');
const names=['A','B','C','D','E'],visitors=['V','W','X','Y','Z'];
function game(id='1'){
 const roster=list=>list.map((name,i)=>({name,starter:i<5,points:i===0?8:0,two_pm:i===0?4:0,two_pa:i===0?4:0,three_pm:0,three_pa:0,ftm:0,fta:0,tov:0})),events=[],add=(period,clock,side,player,type,score)=>events.push({period,clock,side,player,type,score});
 for(let p=1;p<=4;p++){const b=(p-1)*2;add(p,'10:00','home','A','jumpball',b+'-'+b);add(p,'09:00','home','A','fgm',(b+2)+'-'+b);if(p===1){add(p,'08:00','home','E','sub-out','2-0');add(p,'08:00','home','F','sub-in','2-0');}add(p,'07:00','away','V','fgm',(b+2)+'-'+(b+2));if(p===1){add(p,'06:00','home','F','sub-out','2-2');add(p,'06:00','home','E','sub-in','2-2');}for(const side of ['home','away'])for(const name of side==='home'?names:visitors)add(p,'01:00',side,name,'ast',(b+2)+'-'+(b+2));add(p,'00:00','','','end',(b+2)+'-'+(b+2));}
 const raw={two_pm:4,two_pa:4,three_pm:0,three_pa:0,ftm:0,fta:0};return {_dbId:id,home:'H',away:'A',date:'2026-09-0'+id,comp:'League',hs:8,as:8,scoreOrder:'home-away',raw:{home:{...raw},away:{...raw}},players:{home:roster([...names,'F']),away:roster(visitors)},playByPlay:events};
}
const g=game(),mirror=game('2');mirror.home='A';mirror.away='H';mirror.players={home:mirror.players.away,away:mirror.players.home};mirror.playByPlay=mirror.playByPlay.map(e=>({...e,side:e.side==='home'?'away':e.side==='away'?'home':'',score:e.score.split('-').reverse().join('-')}));const entries=global.CourtIQSeasonWorkbench.select(global.CourtIQSeasonWorkbench.prepare([['db_1',g],['db_2',mirror]]),{team:'H'}),original=JSON.stringify(entries);
let r=api.lineups(entries);assert.equal(r.gamesWithIntervals,2);assert.equal(r.seconds,4800);assert.equal(r.expected,4800);assert.equal(r.rows.length,2);assert.equal(r.rows[0].games,2);assert.equal(r.rows[0].minutes,76);assert.equal(r.rows[1].minutes,4);assert.equal(r.rows.reduce((n,x)=>n+x.pointsFor,0),16);assert.equal(r.rows.reduce((n,x)=>n+x.pointsAgainst,0),16);assert.equal(r.rows[0].net,null);assert.equal(api.lineups(entries,{minimum:5}).rows.length,1);assert.equal(api.lineups(entries,{period:'1'}).seconds,1200);assert.equal(api.lineups(entries,{period:'1'}).expected,1200);
const noPbp={...g,playByPlay:[]};r=api.lineups([{key:'none',g:noPbp,side:'home'}]);assert.equal(r.rows.length,0);assert.equal(r.coverage[0].status,'NO_PBP');const bad=structuredClone(g);bad.playByPlay.find(e=>e.type==='sub-in').clock='invalid';assert.equal(api.lineups([{key:'bad',g:bad,side:'home'}]).rows.length,0);
const partial=structuredClone(g);partial.playByPlay=partial.playByPlay.filter(e=>e.type!=='sub-in');r=api.lineups([{key:'partial',g:partial,side:'home'}]);assert.equal(r.coverage[0].status,'PARTIAL');assert.ok(r.seconds<2400);assert.equal(r.expected,2400);
const overtime=game();overtime.playByPlay.push({period:5,clock:'05:00',side:'home',player:'A',type:'jumpball',score:'8-8'});for(const side of ['home','away'])for(const name of side==='home'?names:visitors)overtime.playByPlay.push({period:5,clock:'01:00',side,player:name,type:'ast',score:'8-8'});overtime.playByPlay.push({period:5,clock:'00:00',type:'end',score:'8-8'});r=api.lineups([{key:'ot',g:overtime,side:'home'}],{period:'5'});assert.equal(r.expected,300);assert.equal(r.seconds,300);assert.ok(r.periods.includes(5));
const s=api.scout(entries);assert.equal(s.playerGames,2);assert.equal(s.team.metrics.efg.value,100);assert.equal(s.leaders[0].name,'A');assert.equal(s.leaders[0].rows.length,2);assert.equal(s.leaders[0].summary.fga,8);assert.equal(s.prompts.length,2);assert.match(api.briefingText(entries,s,'H'),/not verified tactical tendencies/);const incomplete=structuredClone(g);incomplete.players.home[0].points=7;assert.equal(api.scout([{key:'bad',g:incomplete,side:'home'}]).playerGames,0);assert.equal(JSON.stringify(entries),original);assert.throws(()=>api.lineups(entries,{minimum:-1}),/minutes/);
console.log('Tactical workspace: reconciled scouting, roster coverage, pooled home/away lineups, minutes, source stints, partial/missing/invalid PBP, overtime and immutability passed.');
