const assert=require('node:assert/strict');global.CourtIQDecisionLab=require('../decision-lab');global.CourtIQPlayerScan=require('../player-scan');const api=require('../season-workbench');
const game=(id,date,made=1,attempts=2)=>({_dbId:id,date,home:'H',away:'A',hs:2*made,as:0,comp:'League',raw:{home:{two_pm:made,two_pa:attempts,three_pm:0,three_pa:0,ftm:0,fta:0},away:{two_pm:0,two_pa:0,three_pm:0,three_pa:0,ftm:0,fta:0}},players:{home:[{name:'P',points:2*made,two_pm:made,two_pa:attempts,three_pm:0,three_pa:0,ftm:0,fta:0,minutes:null}]}});
assert.equal(api.dateValue('31/02/2026'),null);assert.equal(api.dateValue('New game'),null);assert.equal(api.dateValue('September 17, 2026'),Date.UTC(2026,8,17));assert.equal(api.dateValue('17.09.2026'),Date.UTC(2026,8,17));assert.equal(api.season(game('x','2026-06-30')),'2025–26');assert.equal(api.season(game('x','2026-07-01')),'2026–27');assert.equal(api.season({...game('x','2026-07-01'),season:'Source season'}),'Source season');
const g1=game('1','2026-09-01',1,1),g2=game('2','2026-09-02',0,9),entries=[['db_1',g1],['db_2',g2],['g1',{...g1,_dbId:undefined}],['pilot',g1]],original=JSON.stringify(entries),data=api.prepare(entries);assert.equal(data.entries.length,2);assert.equal(data.excluded,2);const rows=api.teamRows(api.select(data,{team:'H'})),a=api.aggregate(rows);assert.equal(a.metrics.efg.value,10,'pooled attempts, not mean of 100% and 0%');assert.equal(a.metrics.points.value,1);assert.equal(a.metrics.ts.value,10);assert.equal(a.metrics.three.value,null);assert.equal(api.aggregate(api.playerRows(api.select(data,{team:'H'}),'P')).metrics.minutes.value,null,'missing minutes must not become zero');
assert.equal(api.select(data,{team:'H',venue:'away'}).length,0);assert.equal(api.select(data,{team:'H',opponent:'Other'}).length,0);assert.equal(api.select(data,{team:'A',venue:'away',competition:'League',season:'2026–27'}).length,2);assert.equal(api.select(data,{team:'H',from:'2026-09-02'}).length,1);
const many=Array.from({length:6},(_,i)=>['db_'+i,game(String(i),'2026-09-0'+(i+1),i<3?0:1,2)]);let c=api.compare(api.teamRows(api.select(api.prepare(many),{team:'H'})),3);assert.equal(c.ready,true);assert.equal(c.delta.efg,50);assert.equal(c.delta.points,2);c=api.compare(api.teamRows(api.select(api.prepare(many.slice(1)),{team:'H'})),3);assert.equal(c.ready,false);assert.equal(c.delta.efg,null);const unknown=[...many,['db_unknown',game('u','unknown')]];c=api.compare(api.teamRows(api.select(api.prepare(unknown),{team:'H'})),3);assert.equal(c.unknownDates,1);assert.equal(c.recent.games,3);assert.equal(c.all.games,7);
const missing=structuredClone(many);delete missing[5][1].raw;c=api.compare(api.teamRows(api.select(api.prepare(missing),{team:'H'})),3);assert.equal(c.ready,true);assert.equal(c.recent.metrics.efg.n,2);assert.equal(c.delta.efg,null);assert.equal(c.delta.points,2);
const dup=api.prepare([['db_old',{...g1,sourceUrl:'https://example.com/game/1?utm_source=a'}],['db_new',{...g2,sourceUrl:'https://example.com/game/1'}]]);assert.equal(dup.entries.length,1);assert.equal(dup.duplicates,1);assert.equal(dup.entries[0].key,'db_new');assert.equal(api.prepare(entries.filter(([k])=>k==='g1'),true).demo,true);assert.equal(api.playerRows(api.select(data,{team:'H'}),'Other').length,0);assert.equal(JSON.stringify(entries),original);assert.throws(()=>api.compare(rows,2),/window/);
console.log('Season workbench: source isolation, pooled rates, complete windows, per-metric coverage, missing minutes, dates, filters, duplicates and immutability passed.');
