const assert=require('node:assert/strict');
global.CourtIQLineupEngine=require('../lineup-engine');
const api=require('../game-intelligence');
const roster=(prefix,ot=false)=>Array.from({length:5},(_,i)=>({name:prefix+i,starter:true,minutes:ot?45:40,points:2}));
const game=()=>({home:'H',away:'A',hs:10,as:10,quarters:[[2,2],[2,2],[2,2],[4,4]],players:{home:roster('H'),away:roster('A')},factors:[['eFG%',50,40],['TOV%',10,20],['ORB%',30,30],['FTr',20,25]]});
let g=game();assert.equal(api.qa(g).failed,0);assert.equal(api.qa(g).unknown,0);assert.equal(api.insights(g).length,3);assert.equal(api.insights(g).find(x=>x.title==='Ball security').finding.startsWith('H'),true);
g=game();g.players.home.forEach(p=>p.starter=false);assert.equal(api.role(g,'home',g.players.home[0]),'Unknown');assert.ok(api.qa(g).unknown>0);
g=game();delete g.players.home[0].points;assert.equal(api.qa(g).checks[0].ok,null);
g=game();g.players.home[0].points=5;assert.equal(api.qa(g).checks[0].ok,false);
g=game();g.quarters.push([0,0]);g.players={home:roster('H',true),away:roster('A',true)};assert.equal(api.qa(g).failed,0);
assert.equal(api.factorRows({factors:[['eFG%','',40]]})[0].a,null);
assert.equal(api.insights({factors:[['eFG%',null,40]]}).length,0);
g=game();g.home='<img src=x>';g.sourceUrl='javascript:alert(1)';assert.ok(!api.render(g).includes('<img'));assert.ok(!api.render(g).includes('javascript:'));
assert.match(api.render(game()),/LOCAL|DEMO/);assert.match(api.render({...game(),_dbId:123}),/SAVED GAME/);
// A first-quarter lineup anchored by official PBP can resolve stale all-bench markers.
g=game();g.players.home.forEach(p=>p.starter=false);g.playByPlay=[];
for(const side of ['home','away'])for(const p of g.players[side])g.playByPlay.push({period:1,clock:'10:00',side,player:p.name,type:'ast',score:'0-0'});
g.playByPlay.push({period:1,clock:'09:00',side:'home',player:'H0',type:'ast',score:'0-0'});g.scoreOrder='home-away';assert.equal(api.starters(g,'home').source,'PLAY-BY-PLAY');assert.equal(api.role(g,'home',g.players.home[0]),'Starter');
console.log('Game intelligence: score QA, missing data, overtime, unknown roles, PBP starters, provenance and escaping passed.');

// A team perspective orders disadvantages before advantages and reverses wording correctly.
g=game();let home=api.insights(g,'home'),away=api.insights(g,'away');
assert.equal(home[0].key,'FTr');assert.match(home[0].finding,/H trailed/);assert.equal(home[0].signal,'REVIEW PRIORITY');
assert.match(away.find(x=>x.key==='TOV%').finding,/A trailed/);
g.players.home[0].points=20;assert.match(api.insights(g)[0].confidence,/DATA REVIEW REQUIRED/);
const output=api.printable({...game(),home:'<script>bad()</script>'},'away');
assert.ok(!output.includes('<script>'));assert.ok(!output.includes('briefExport'));assert.match(output,/Focus: A/);assert.match(output,/save it as PDF/);
assert.match(api.render(game(),'away'),/value="away" selected/);
assert.match(api.render(game()),/data-factor="TOV%"/);
// Video review is isolated by game, focus and factor; corrections invalidate reviewed status.
const reviewStorage=new Map();global.localStorage={getItem:k=>reviewStorage.get(k)||null,setItem:(k,v)=>reviewStorage.set(k,v)};
g=game();g.id='review1';
assert.throws(()=>api.saveReview(g,'home','TOV%',{reviewed:true,note:'Short'}),/supporting video/);
assert.throws(()=>api.saveReview(g,'home','TOV%',{support:'javascript:alert(1)'}),/HTTPS/);
api.saveReview(g,'home','TOV%',{reviewed:true,note:'Pressure forced this turnover. <script>bad()</script>',support:'https://youtu.be/abc?t=60',counter:'https://youtu.be/abc?t=90'});
assert.equal(api.readReview(g,'home','TOV%').reviewed,true);
assert.equal(api.readReview(g,'away','TOV%').reviewed,undefined);
assert.equal(api.readReview({...g,id:'other'},'home','TOV%').reviewed,undefined);
let printed=api.printable(g,'home');assert.match(printed,/REVIEWED LOCALLY/);assert.match(printed,/Supporting clip/);assert.match(printed,/Counterexample/);assert.ok(!printed.includes('<script>bad()'));
g.factors[1][1]=11;assert.equal(api.readReview(g,'home','TOV%').stale,true);assert.equal(api.readReview(g,'home','TOV%').reviewed,false);assert.match(api.render(g,'home'),/STATS CHANGED/);
api.saveReview(g,'home','TOV%',{note:'Corrected values reviewed',support:'https://example.com/clip',reviewed:true});assert.equal(api.readReview(g,'home','TOV%').stale,false);
const official={...g,sourceUrl:'https://example.com/game/1/'};assert.equal(api.reviewKey(official,'home','TOV%'),api.reviewKey({...official,_dbId:12,sourceUrl:official.sourceUrl+'?utm_source=chatgpt'},'home','TOV%'));
global.localStorage={getItem:()=>null,setItem:()=>{throw new Error('Storage full')}};assert.throws(()=>api.saveReview(g,'home','TOV%',{note:'Draft'}),/Storage full/);
delete global.localStorage;
global.CourtIQDecisionLab=require('../decision-lab');global.CourtIQPlayerScan=require('../player-scan');global.CourtIQAnalyticsEngine=require('../analytics-engine');
const prep={id:'prep',home:'H',away:'A',hs:7,as:0,raw:{home:{two_pm:1,two_pa:2,three_pm:1,three_pa:2,ftm:2,fta:2},away:{two_pm:0,two_pa:0,three_pm:0,three_pa:0,ftm:0,fta:0}},quarters:[[7,0],[0,0],[0,0],[0,0]],players:{home:[{name:'P <script>',points:7,two_pm:1,two_pa:2,three_pm:1,three_pa:2,ftm:2,fta:2}],away:[]},factors:[]};
assert.equal(api.coachPlan(prep,'').length,0);assert.deepEqual(api.coachPlan(prep,'home').map(p=>p.kind),['TEAM','PLAYER','PERIOD']);assert.match(api.coachPlan(prep,'home')[1].fact,/100.0%/);assert.equal(api.coachPlan({...prep,hs:8},'home').length,0);assert.ok(!api.render(prep,'home').includes('<script>'));assert.match(api.render(prep,'home'),/SAVE COACH PLAN/);
const planStore=new Map();global.localStorage={getItem:k=>planStore.get(k)||null,setItem:(k,v)=>planStore.set(k,v)};
assert.throws(()=>api.savePlan(prep,'',{}),/focus team/);api.savePlan(prep,'home',{priority:'Protect the ball <script>',adjustment:'Test a change if confirmed',watch:'Count attempts'});assert.equal(api.readPlan(prep,'home').stale,false);assert.equal(api.readPlan(prep,'away').priority,undefined);assert.equal(api.readPlan({...prep,id:'other'},'home').priority,undefined);assert.equal(api.readPlan({...prep,hs:8},'home').stale,true);assert.match(api.printable(prep,'home'),/Protect the ball &lt;script&gt;/);assert.ok(!api.printable(prep,'home').includes('coachPlanSave'));assert.match(api.printable(prep,'home'),/Highest field-goal attempt volume/);
global.localStorage={getItem:()=>null,setItem:()=>{throw new Error('Storage full')}};assert.throws(()=>api.savePlan(prep,'home',{}),/Storage full/);delete global.localStorage;
console.log('Coach preparation: reconciled team/player/period prompts, safe export, team/game isolation, data-change warning and storage failures passed.');
console.log('Brief reviews: local persistence, game/team isolation, safe links, escaped export, revised-data invalidation and storage failures passed.');
