-- Mirrors the production CourtIQ Supabase schema applied 2026-09-22.
-- RLS scopes all video/tactical rows to existing club membership.
create table if not exists public.game_videos (
 id bigint generated by default as identity primary key,
 game_id bigint not null references public.games(id) on delete cascade,
 club_id bigint not null references public.clubs(id) on delete cascade,
 storage_bucket text, storage_path text, playback_url text,
 duration_seconds numeric, fps numeric,
 status text not null default 'ready' check (status in ('uploading','ready','processing','failed')),
 created_by uuid not null default auth.uid() references auth.users(id),
 created_at timestamptz not null default now()
);
create index if not exists game_videos_game_id_idx on public.game_videos(game_id);
create index if not exists game_videos_club_id_idx on public.game_videos(club_id);
create index if not exists game_videos_created_by_idx on public.game_videos(created_by);
alter table public.game_videos enable row level security;

create table if not exists public.tactical_events (
 id bigint generated by default as identity primary key,
 game_id bigint not null references public.games(id) on delete cascade,
 video_id bigint references public.game_videos(id) on delete cascade,
 club_id bigint not null references public.clubs(id) on delete cascade,
 external_event_id text, period integer, game_clock text,
 video_start numeric not null, video_time numeric not null, video_end numeric not null,
 offense_team text, defense_team text, action_type text not null, coverage_type text,
 ball_handler_ref text, screener_ref text, outcome_type text,
 points integer not null default 0, tags jsonb not null default '[]'::jsonb,
 confidence jsonb not null default '{}'::jsonb,
 verification text not null default 'ai' check (verification in ('ai','human','human_corrected')),
 model_version text, evidence jsonb not null default '{}'::jsonb,
 created_by uuid default auth.uid() references auth.users(id),
 created_at timestamptz not null default now(),
 check (video_start >= 0 and video_time >= video_start and video_end >= video_time)
);
create index if not exists tactical_events_game_id_idx on public.tactical_events(game_id);
create index if not exists tactical_events_video_id_idx on public.tactical_events(video_id);
create index if not exists tactical_events_club_id_idx on public.tactical_events(club_id);
create index if not exists tactical_events_created_by_idx on public.tactical_events(created_by);
create index if not exists tactical_events_action_coverage_idx on public.tactical_events(action_type,coverage_type);
alter table public.tactical_events enable row level security;
