create table if not exists public.intelligence_claims(
 id bigint generated by default as identity primary key,
 club_id bigint references public.clubs(id) on delete cascade,
 game_id bigint references public.games(id) on delete cascade,
 competition text not null,
 subject_type text not null check(subject_type in ('team','player','game','opponent')),
 subject_name text not null, claim_type text not null, claim_text text not null,
 data jsonb not null default '{}'::jsonb, sample_games integer not null default 0,
 sample_minutes numeric, evidence_game_ids bigint[] not null default '{}',
 video_evidence jsonb not null default '[]'::jsonb, confidence numeric check(confidence between 0 and 1),
 status text not null default 'INSUFFICIENT_DATA' check(status in ('VERIFIED','INSUFFICIENT_DATA','REVIEW')),
 created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);
alter table public.intelligence_claims enable row level security;
grant select on public.intelligence_claims to authenticated;
create policy "competition access intelligence claims" on public.intelligence_claims for select to authenticated using(public.can_access_competition(competition));
create table if not exists public.data_quality_checks(
 id bigint generated by default as identity primary key, game_id bigint not null references public.games(id) on delete cascade,
 check_name text not null, status text not null check(status in ('PASS','FAIL','WARN')), expected jsonb, actual jsonb, details text,
 created_at timestamptz not null default now(), unique(game_id,check_name)
);
alter table public.data_quality_checks enable row level security; grant select on public.data_quality_checks to authenticated;
create policy "competition access quality checks" on public.data_quality_checks for select to authenticated using(exists(select 1 from public.games g where g.id=data_quality_checks.game_id and public.can_access_competition(coalesce(g.competition,''))));
create table if not exists public.user_profiles(user_id uuid primary key references auth.users(id) on delete cascade,role text not null default 'viewer' check(role in ('owner','coach','analyst','viewer')),display_name text,last_seen_at timestamptz,created_at timestamptz not null default now());
alter table public.user_profiles enable row level security; grant select on public.user_profiles to authenticated;
create policy "users read own profile" on public.user_profiles for select to authenticated using(user_id=(select auth.uid()) or (select auth.uid())='10fa3b29-4acd-4fcf-9784-1117b510332c'::uuid);
insert into public.user_profiles(user_id,role,display_name) values('10fa3b29-4acd-4fcf-9784-1117b510332c'::uuid,'owner','CourtIQ Owner') on conflict(user_id) do update set role='owner';
create or replace function public.team_memory(comp text,team text) returns jsonb language sql stable security invoker set search_path=public as $$
with x as(select id,game_date,home_team,away_team,payload,row_number()over(order by game_date desc nulls last,id desc)rn from public.games where competition=comp and(home_team=team or away_team=team)),m as(select *,case when home_team=team then(payload->'ui'->'metrics'->'home'->>'pace')::numeric else(payload->'ui'->'metrics'->'away'->>'pace')::numeric end pace,case when home_team=team then(payload->'ui'->>'homeScore')::numeric else(payload->'ui'->>'awayScore')::numeric end pts from x) select jsonb_build_object('competition',comp,'team',team,'games',count(*),'season',jsonb_build_object('games',count(*),'pace',round(avg(pace),1),'ppg',round(avg(pts),1)),'last10',jsonb_build_object('games',count(*)filter(where rn<=10),'pace',round(avg(pace)filter(where rn<=10),1),'ppg',round(avg(pts)filter(where rn<=10),1)),'last5',jsonb_build_object('games',count(*)filter(where rn<=5),'pace',round(avg(pace)filter(where rn<=5),1),'ppg',round(avg(pts)filter(where rn<=5),1)),'last3',jsonb_build_object('games',count(*)filter(where rn<=3),'pace',round(avg(pace)filter(where rn<=3),1),'ppg',round(avg(pts)filter(where rn<=3),1)))from m;$$;
revoke all on function public.team_memory(text,text) from public,anon;grant execute on function public.team_memory(text,text) to authenticated;