create table if not exists public.client_health_events (
  id bigint generated by default as identity primary key,
  club_id bigint not null references public.clubs(id) on delete cascade,
  user_id uuid not null default auth.uid(),
  event_type text not null check (event_type = any (array['error'::text,'unhandled_rejection'::text,'performance'::text,'action_failure'::text])),
  module text not null default 'app',
  severity text not null default 'warning' check (severity = any (array['info'::text,'warning'::text,'error'::text,'critical'::text])),
  message text not null check (char_length(message) <= 500),
  metadata jsonb not null default '{}'::jsonb check (jsonb_typeof(metadata) = 'object'),
  occurred_at timestamptz not null default now()
);

create index if not exists client_health_events_club_time_idx
  on public.client_health_events (club_id, occurred_at desc);
create index if not exists client_health_events_type_time_idx
  on public.client_health_events (event_type, occurred_at desc);

alter table public.client_health_events enable row level security;

create policy "members create own health events"
on public.client_health_events for insert
to authenticated
with check (
  user_id = (select auth.uid())
  and private.is_club_member(club_id)
);

create policy "admin analyst read health events"
on public.client_health_events for select
to authenticated
using (
  exists (
    select 1 from public.club_members m
    where m.club_id = client_health_events.club_id
      and m.user_id = (select auth.uid())
      and m.role = any (array['admin'::text,'analyst'::text])
  )
);

revoke all on public.client_health_events from anon;
grant insert on public.client_health_events to authenticated;
grant select on public.client_health_events to authenticated;
grant usage, select on sequence public.client_health_events_id_seq to authenticated;
