-- CourtIQ v187 · Player 360 + GM / Recruitment foundation.
-- Adds canonical player identity links, basketball-ops needs/shortlists and read RPCs.

create table if not exists public.player_identity_links (
  id bigint generated by default as identity primary key,
  club_id bigint not null references public.clubs(id) on delete cascade,
  canonical_player_id bigint not null references public.players(id) on delete cascade,
  source_player_id bigint not null references public.players(id) on delete cascade,
  source_label text not null default 'official game import',
  confidence numeric not null default 1 check (confidence >= 0 and confidence <= 1),
  evidence jsonb not null default '{}'::jsonb,
  verified boolean not null default false,
  created_at timestamptz not null default now(),
  unique (club_id, canonical_player_id, source_player_id)
);

create index if not exists player_identity_links_canonical_idx on public.player_identity_links(club_id,canonical_player_id);
create index if not exists player_identity_links_source_idx on public.player_identity_links(source_player_id);
alter table public.player_identity_links enable row level security;
drop policy if exists "members_read_identity_links" on public.player_identity_links;
create policy "members_read_identity_links" on public.player_identity_links
for select to authenticated using (private.is_club_member(club_id));

create table if not exists public.club_roster_needs (
  id bigint generated by default as identity primary key,
  club_id bigint not null references public.clubs(id) on delete cascade,
  season text not null,
  role_key text not null,
  label text not null,
  priority text not null default 'medium' check (priority in ('low','medium','high')),
  target_profile jsonb not null default '{}'::jsonb,
  notes text,
  active boolean not null default true,
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  unique (club_id,season,role_key)
);

create table if not exists public.recruitment_shortlist (
  id bigint generated by default as identity primary key,
  club_id bigint not null references public.clubs(id) on delete cascade,
  season text not null,
  player_id bigint not null references public.players(id) on delete cascade,
  role_key text,
  status text not null default 'watch' check (status in ('watch','shortlist','review','contacted','closed')),
  notes text,
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (club_id,season,player_id)
);

alter table public.club_roster_needs enable row level security;
alter table public.recruitment_shortlist enable row level security;

drop policy if exists "members_read_roster_needs" on public.club_roster_needs;
create policy "members_read_roster_needs" on public.club_roster_needs
for select to authenticated using (private.is_club_member(club_id));

drop policy if exists "ops_manage_roster_needs" on public.club_roster_needs;
create policy "ops_manage_roster_needs" on public.club_roster_needs
for all to authenticated
using (exists (select 1 from public.club_members m where m.club_id=club_roster_needs.club_id and m.user_id=auth.uid() and m.role in ('owner','admin','gm','analyst','scout')))
with check (exists (select 1 from public.club_members m where m.club_id=club_roster_needs.club_id and m.user_id=auth.uid() and m.role in ('owner','admin','gm','analyst','scout')));

drop policy if exists "members_read_recruitment_shortlist" on public.recruitment_shortlist;
create policy "members_read_recruitment_shortlist" on public.recruitment_shortlist
for select to authenticated using (private.is_club_member(club_id));

drop policy if exists "ops_manage_recruitment_shortlist" on public.recruitment_shortlist;
create policy "ops_manage_recruitment_shortlist" on public.recruitment_shortlist
for all to authenticated
using (exists (select 1 from public.club_members m where m.club_id=recruitment_shortlist.club_id and m.user_id=auth.uid() and m.role in ('owner','admin','gm','analyst','scout')))
with check (exists (select 1 from public.club_members m where m.club_id=recruitment_shortlist.club_id and m.user_id=auth.uid() and m.role in ('owner','admin','gm','analyst','scout')));

-- Known Ashdod canonical roster ↔ official Hebrew import identities. IDs are resolved by names, never hardcoded.
with map(canonical_name,source_name) as (
  values
    ('Abby Meyers','אביגיל מיירס'),
    ('Anja Fuchs-Robetin','אניה פוקס-רובטין'),
    ('Jazmine Jones','ג''זמין ג''ונס'),
    ('Gal Cohen','גל כהן'),
    ('Dor Saar','דור סער'),
    ('Dalayah Daniels','דלאיה דניאלס'),
    ('Yahel Jovanovic','יהל יובנוביץ'),
    ('Paula Estebas','פאולה אסטבס ארמס'),
    ('Tzilil Vaturi','צליל וטורי'),
    ('Kat Vuckovic','קטרינה ווקוביץ''')
)
insert into public.player_identity_links (club_id,canonical_player_id,source_player_id,source_label,confidence,evidence,verified)
select c.id,pc.id,ps.id,'IBBA official game import',1,
       jsonb_build_object('canonical_name',m.canonical_name,'source_name',m.source_name,'method','verified roster alias'),true
from map m
join public.clubs c on c.slug='maccabi-bnot-ashdod'
join public.players pc on lower(pc.name)=lower(m.canonical_name)
join public.players ps on ps.name=m.source_name
on conflict (club_id,canonical_player_id,source_player_id) do update
set confidence=excluded.confidence,evidence=excluded.evidence,verified=true;

create or replace function public.player_360_snapshot(p_club_id bigint,p_player_id bigint,p_season text default null)
returns jsonb
language plpgsql stable security definer set search_path=public
as $$
declare
  result jsonb;
begin
  if not private.is_club_member(p_club_id) then raise exception 'not authorized'; end if;
  if not exists (select 1 from public.club_players cp where cp.club_id=p_club_id and cp.player_id=p_player_id) then
    raise exception 'player is not in this club workspace';
  end if;
  with ids as (
    select p_player_id as id
    union
    select source_player_id from public.player_identity_links where club_id=p_club_id and canonical_player_id=p_player_id and verified=true
  ), base as (
    select p.id,p.name,p.position,p.nationality,p.source_url,p.analysis,cp.season,cp.roster_status
    from public.players p join public.club_players cp on cp.player_id=p.id and cp.club_id=p_club_id
    where p.id=p_player_id
  ), samples as (
    select coalesce(jsonb_agg(to_jsonb(s) order by s.season desc,s.created_at desc),'[]'::jsonb) j
    from public.player_samples s where s.player_id in (select id from ids) and (p_season is null or s.season=p_season)
  ), games as (
    select coalesce(jsonb_agg(jsonb_build_object(
      'id',g.id,'game_id',g.game_id,'season',g.season,'competition',g.competition,'team_name',g.team_name,
      'opponent_name',g.opponent_name,'player_name',g.player_name,'starter',g.starter,'minutes',g.minutes,
      'stats',g.stats,'calculated',g.calculated,'source_url',g.source_url,'created_at',g.created_at
    ) order by g.created_at desc),'[]'::jsonb) j
    from public.game_player_stats g where g.player_id in (select id from ids) and g.verified=true and (p_season is null or g.season=p_season)
  ), aliases as (
    select coalesce(jsonb_agg(jsonb_build_object('source_player_id',l.source_player_id,'source_label',l.source_label,'confidence',l.confidence,'evidence',l.evidence,'verified',l.verified)),'[]'::jsonb) j
    from public.player_identity_links l where l.club_id=p_club_id and l.canonical_player_id=p_player_id
  )
  select jsonb_build_object('player',to_jsonb(base),'aliases',aliases.j,'samples',samples.j,'game_stats',games.j)
  into result from base,samples,games,aliases;
  return coalesce(result,'{}'::jsonb);
end;$$;

create or replace function public.basketball_ops_snapshot(p_club_id bigint,p_season text default null)
returns jsonb
language plpgsql stable security definer set search_path=public
as $$
declare result jsonb;
begin
  if not private.is_club_member(p_club_id) then raise exception 'not authorized'; end if;
  with club_players_json as (
    select coalesce(jsonb_agg(jsonb_build_object(
      'club_id',cp.club_id,'player_id',cp.player_id,'season',cp.season,'roster_status',cp.roster_status,
      'player',jsonb_build_object('id',p.id,'name',p.name,'position',p.position,'nationality',p.nationality,'source_url',p.source_url,'analysis',p.analysis),
      'source_ids',coalesce((select jsonb_agg(l.source_player_id) from public.player_identity_links l where l.club_id=p_club_id and l.canonical_player_id=p.id and l.verified=true),'[]'::jsonb)
    ) order by cp.roster_status,p.name),'[]'::jsonb) j
    from public.club_players cp join public.players p on p.id=cp.player_id
    where cp.club_id=p_club_id and (p_season is null or cp.season=p_season)
  ), canonical_ids as (
    select cp.player_id from public.club_players cp where cp.club_id=p_club_id and (p_season is null or cp.season=p_season)
  ), all_ids as (
    select player_id id from canonical_ids
    union
    select l.source_player_id from public.player_identity_links l where l.club_id=p_club_id and l.canonical_player_id in (select player_id from canonical_ids) and l.verified=true
  ), samples_json as (
    select coalesce(jsonb_agg(to_jsonb(s) order by s.created_at desc),'[]'::jsonb) j
    from public.player_samples s where s.player_id in (select id from all_ids) and (p_season is null or s.season=p_season)
  ), game_json as (
    select coalesce(jsonb_agg(jsonb_build_object(
      'player_id',g.player_id,'player_name',g.player_name,'game_id',g.game_id,'season',g.season,'competition',g.competition,
      'team_name',g.team_name,'opponent_name',g.opponent_name,'starter',g.starter,'minutes',g.minutes,'stats',g.stats,'calculated',g.calculated,'created_at',g.created_at
    ) order by g.created_at desc),'[]'::jsonb) j
    from public.game_player_stats g where g.player_id in (select id from all_ids) and g.verified=true and (p_season is null or g.season=p_season)
  ), needs_json as (
    select coalesce(jsonb_agg(to_jsonb(n) order by case n.priority when 'high' then 1 when 'medium' then 2 else 3 end,n.created_at),'[]'::jsonb) j
    from public.club_roster_needs n where n.club_id=p_club_id and n.active=true and (p_season is null or n.season=p_season)
  ), shortlist_json as (
    select coalesce(jsonb_agg(jsonb_build_object('id',r.id,'player_id',r.player_id,'season',r.season,'role_key',r.role_key,'status',r.status,'notes',r.notes,'player',jsonb_build_object('name',p.name,'position',p.position)) order by r.updated_at desc),'[]'::jsonb) j
    from public.recruitment_shortlist r join public.players p on p.id=r.player_id
    where r.club_id=p_club_id and (p_season is null or r.season=p_season)
  )
  select jsonb_build_object('club_players',club_players_json.j,'samples',samples_json.j,'game_stats',game_json.j,'needs',needs_json.j,'shortlist',shortlist_json.j)
  into result from club_players_json,samples_json,game_json,needs_json,shortlist_json;
  return result;
end;$$;

revoke all on function public.player_360_snapshot(bigint,bigint,text) from public;
revoke all on function public.basketball_ops_snapshot(bigint,text) from public;
grant execute on function public.player_360_snapshot(bigint,bigint,text) to authenticated;
grant execute on function public.basketball_ops_snapshot(bigint,text) to authenticated;

grant select on public.player_identity_links,public.club_roster_needs,public.recruitment_shortlist to authenticated;
grant insert,update,delete on public.club_roster_needs,public.recruitment_shortlist to authenticated;
grant usage,select on sequence public.club_roster_needs_id_seq,public.recruitment_shortlist_id_seq to authenticated;
