-- CourtIQ Billing Bridge v217
-- Stripe remains an external payment processor; CourtIQ remains the source of truth for product entitlements.

create table if not exists public.billing_webhook_events (
  id bigint generated by default as identity primary key,
  provider text not null,
  provider_event_id text not null,
  event_type text not null,
  object_id text,
  club_id bigint references public.clubs(id) on delete set null,
  status text not null default 'processing',
  event_created_at timestamptz,
  processed_at timestamptz,
  error_message text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint billing_webhook_events_status_check check (status in ('processing','processed','failed')),
  constraint billing_webhook_events_provider_event_key unique(provider, provider_event_id)
);

alter table public.billing_webhook_events enable row level security;
revoke all on public.billing_webhook_events from public, anon, authenticated;

create index if not exists billing_webhook_events_club_idx
  on public.billing_webhook_events(club_id, created_at desc);
create index if not exists billing_webhook_events_status_idx
  on public.billing_webhook_events(status, created_at desc);

comment on table public.billing_webhook_events is
  'Private idempotency/audit log for external billing webhook events. Service-role only.';

-- Admin-facing helper view. Does not expose provider customer/subscription IDs.
create or replace view public.club_billing_status
with (security_invoker = true)
as
select
  e.club_id,
  e.plan_code,
  e.plan_name,
  e.status,
  e.payment_provider,
  e.current_period_start,
  e.current_period_end,
  e.trial_ends_at,
  e.cancel_at_period_end,
  e.monthly_game_limit,
  e.seat_limit,
  e.features,
  e.games_used,
  e.games_remaining,
  e.can_import_game,
  (s.provider_customer_id is not null) as billing_customer_ready,
  (s.provider_subscription_id is not null) as billing_subscription_ready
from public.club_entitlement_status e
join public.club_subscriptions s on s.club_id=e.club_id;

revoke all on public.club_billing_status from public, anon;
grant select on public.club_billing_status to authenticated;
