create table if not exists public.postgame_reviews (
  id bigint generated by default as identity primary key,
  club_id bigint not null references public.clubs(id) on delete cascade,
  game_id bigint not null references public.games(id) on delete cascade,
  pregame_report_id bigint references public.saved_reports(id) on delete set null,
  opponent_name text not null,
  competition text,
  payload jsonb not null default '{}'::jsonb,
  review_version integer not null default 1 check (review_version > 0),
  reviewed_by uuid not null default auth.uid(),
  reviewed_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (club_id, game_id),
  check (jsonb_typeof(payload) = 'object')
);

create index if not exists postgame_reviews_club_reviewed_idx
  on public.postgame_reviews (club_id, reviewed_at desc);
create index if not exists postgame_reviews_game_idx
  on public.postgame_reviews (game_id);

alter table public.postgame_reviews enable row level security;

create policy "club members read postgame reviews"
on public.postgame_reviews for select
to authenticated
using (
  private.is_club_member(club_id)
  and can_access_competition(coalesce(competition, ''))
);

create policy "staff create postgame reviews"
on public.postgame_reviews for insert
to authenticated
with check (
  reviewed_by = (select auth.uid())
  and exists (
    select 1 from public.games g
    where g.id = postgame_reviews.game_id
      and g.club_id = postgame_reviews.club_id
      and can_access_competition(coalesce(g.competition, ''))
  )
  and exists (
    select 1 from public.club_members m
    where m.club_id = postgame_reviews.club_id
      and m.user_id = (select auth.uid())
      and m.role = any (array['admin'::text,'coach'::text,'analyst'::text])
  )
);

create policy "staff update postgame reviews"
on public.postgame_reviews for update
to authenticated
using (
  exists (
    select 1 from public.club_members m
    where m.club_id = postgame_reviews.club_id
      and m.user_id = (select auth.uid())
      and m.role = any (array['admin'::text,'coach'::text,'analyst'::text])
  )
)
with check (
  reviewed_by = (select auth.uid())
  and exists (
    select 1 from public.games g
    where g.id = postgame_reviews.game_id
      and g.club_id = postgame_reviews.club_id
      and can_access_competition(coalesce(g.competition, ''))
  )
);

revoke all on public.postgame_reviews from anon;
grant select, insert, update on public.postgame_reviews to authenticated;
grant usage, select on sequence public.postgame_reviews_id_seq to authenticated;
