-- CourtIQ Product V1 club/player model.
-- This migration mirrors the schema applied to the free Supabase pilot project.
create table if not exists public.clubs (
  id bigint generated by default as identity primary key,
  slug text not null unique, name text not null,
  season text not null default '2026-27', country text not null default 'Israel',
  competition text, pilot boolean not null default false,
  created_at timestamptz not null default now()
);
create table if not exists public.club_members (
  club_id bigint not null references public.clubs(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  role text not null default 'analyst' check (role in ('admin','coach','analyst','viewer')),
  created_at timestamptz not null default now(), primary key (club_id,user_id)
);
create table if not exists public.players (
  id bigint generated by default as identity primary key, external_id text,
  name text not null, position text, nationality text, source_url text,
  created_at timestamptz not null default now()
);
create unique index if not exists players_external_id_uq on public.players(external_id) where external_id is not null;
create table if not exists public.club_players (
  club_id bigint not null references public.clubs(id) on delete cascade,
  player_id bigint not null references public.players(id) on delete cascade,
  season text not null,
  roster_status text not null default 'scouting' check (roster_status in ('roster','scouting','opponent')),
  created_at timestamptz not null default now(), primary key (club_id,player_id,season)
);
create table if not exists public.player_samples (
  id bigint generated by default as identity primary key,
  player_id bigint not null references public.players(id) on delete cascade,
  season text not null, competition text not null, club_name text, phase text,
  games integer, minutes numeric, raw_stats jsonb not null default '{}'::jsonb,
  published_summary jsonb not null default '{}'::jsonb,
  source_label text not null, source_url text, source_note text,
  verified boolean not null default false, created_at timestamptz not null default now()
);
alter table public.games add column if not exists club_id bigint references public.clubs(id) on delete set null;
create index if not exists games_club_id_idx on public.games(club_id);
create index if not exists player_samples_player_id_idx on public.player_samples(player_id);
create index if not exists club_players_club_id_idx on public.club_players(club_id);
alter table public.clubs enable row level security;
alter table public.club_members enable row level security;
alter table public.players enable row level security;
alter table public.club_players enable row level security;
alter table public.player_samples enable row level security;
insert into public.clubs (slug,name,season,country,competition,pilot)
values ('maccabi-bnot-ashdod','Maccabi Bnot Ashdod','2026-27','Israel','Women''s Premier League',true)
on conflict (slug) do update set name=excluded.name,season=excluded.season,country=excluded.country,competition=excluded.competition,pilot=excluded.pilot;
