-- Product V1 persistent reports and player analysis.
alter table public.players add column if not exists analysis jsonb not null default '{}'::jsonb;
create table if not exists public.game_reports (
  id bigint generated by default as identity primary key,
  game_id bigint not null references public.games(id) on delete cascade,
  report_version text not null default 'v1',
  payload jsonb not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(game_id, report_version)
);
alter table public.game_reports enable row level security;
create index if not exists game_reports_game_id_idx on public.game_reports(game_id);
create policy "members_read_game_reports" on public.game_reports for select to authenticated
using (exists (
  select 1 from public.games g where g.id=game_reports.game_id
  and g.club_id is not null and private.is_club_member(g.club_id)
));
