-- Product V1 import audit trail.
create table if not exists public.import_runs (
  id bigint generated by default as identity primary key,
  club_id bigint not null references public.clubs(id) on delete cascade,
  provider text not null,
  source_url text not null,
  external_id text,
  status text not null check (status in ('success','failed')),
  validation jsonb not null default '{}'::jsonb,
  error_message text,
  game_id bigint references public.games(id) on delete set null,
  created_at timestamptz not null default now()
);
alter table public.import_runs enable row level security;
create index if not exists import_runs_club_created_idx on public.import_runs(club_id,created_at desc);
create policy "members_read_import_runs" on public.import_runs
for select to authenticated using (private.is_club_member(club_id));
