-- CourtIQ v186 · Club OS organization / season / team / role foundation.
-- Non-destructive expansion of the existing pilot schema.

alter table public.club_members drop constraint if exists club_members_role_check;
alter table public.club_members add constraint club_members_role_check check (
  role in ('owner','admin','gm','coach','assistant_coach','analyst','scout','player_development','performance','player','viewer')
);

alter table public.user_profiles drop constraint if exists user_profiles_role_check;
alter table public.user_profiles add constraint user_profiles_role_check check (
  role in ('owner','admin','gm','coach','assistant_coach','analyst','scout','player_development','performance','player','viewer')
);

create table if not exists public.club_seasons (
  id bigint generated by default as identity primary key,
  club_id bigint not null references public.clubs(id) on delete cascade,
  season text not null,
  competition text not null default 'Unknown',
  country text,
  is_active boolean not null default false,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  unique (club_id, season, competition)
);

create table if not exists public.club_teams (
  id bigint generated by default as identity primary key,
  club_id bigint not null references public.clubs(id) on delete cascade,
  season_id bigint not null references public.club_seasons(id) on delete cascade,
  name text not null,
  code text,
  gender text,
  level text not null default 'first_team',
  is_primary boolean not null default false,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  unique (club_id, season_id, name)
);

create table if not exists public.club_member_scopes (
  id bigint generated by default as identity primary key,
  club_id bigint not null references public.clubs(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  season_id bigint references public.club_seasons(id) on delete cascade,
  team_id bigint references public.club_teams(id) on delete cascade,
  permissions jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create unique index if not exists club_member_scopes_uq
on public.club_member_scopes (club_id, user_id, coalesce(season_id,0), coalesce(team_id,0));
create index if not exists club_seasons_club_idx on public.club_seasons(club_id,is_active);
create index if not exists club_teams_club_idx on public.club_teams(club_id,season_id);
create index if not exists club_member_scopes_user_idx on public.club_member_scopes(user_id,club_id);

alter table public.club_seasons enable row level security;
alter table public.club_teams enable row level security;
alter table public.club_member_scopes enable row level security;

drop policy if exists "members_read_club_seasons" on public.club_seasons;
create policy "members_read_club_seasons" on public.club_seasons
for select to authenticated using (public.is_club_member(club_id));

drop policy if exists "members_read_club_teams" on public.club_teams;
create policy "members_read_club_teams" on public.club_teams
for select to authenticated using (public.is_club_member(club_id));

drop policy if exists "members_read_own_scopes" on public.club_member_scopes;
create policy "members_read_own_scopes" on public.club_member_scopes
for select to authenticated using (user_id = auth.uid() and public.is_club_member(club_id));

create or replace function public.club_role_permissions(p_role text)
returns jsonb language sql immutable as $$
  select case coalesce(p_role,'viewer')
    when 'owner' then '{"admin":true,"games":true,"live":true,"analytics":true,"players":true,"scouting":true,"reports":true,"video":true,"gm":true,"recruitment":true,"practice":true,"league":true}'::jsonb
    when 'admin' then '{"admin":true,"games":true,"live":true,"analytics":true,"players":true,"scouting":true,"reports":true,"video":true,"gm":true,"recruitment":true,"practice":true,"league":true}'::jsonb
    when 'gm' then '{"admin":false,"games":true,"live":true,"analytics":true,"players":true,"scouting":true,"reports":true,"video":true,"gm":true,"recruitment":true,"practice":false,"league":true}'::jsonb
    when 'coach' then '{"admin":false,"games":true,"live":true,"analytics":true,"players":true,"scouting":true,"reports":true,"video":true,"gm":false,"recruitment":false,"practice":true,"league":true}'::jsonb
    when 'assistant_coach' then '{"admin":false,"games":true,"live":true,"analytics":true,"players":true,"scouting":true,"reports":true,"video":true,"gm":false,"recruitment":false,"practice":true,"league":true}'::jsonb
    when 'analyst' then '{"admin":false,"games":true,"live":true,"analytics":true,"players":true,"scouting":true,"reports":true,"video":true,"gm":false,"recruitment":true,"practice":true,"league":true}'::jsonb
    when 'scout' then '{"admin":false,"games":true,"live":false,"analytics":true,"players":true,"scouting":true,"reports":true,"video":true,"gm":true,"recruitment":true,"practice":false,"league":true}'::jsonb
    when 'player_development' then '{"admin":false,"games":true,"live":true,"analytics":true,"players":true,"scouting":false,"reports":true,"video":true,"gm":false,"recruitment":false,"practice":true,"league":false}'::jsonb
    when 'performance' then '{"admin":false,"games":true,"live":true,"analytics":true,"players":true,"scouting":false,"reports":true,"video":true,"gm":false,"recruitment":false,"practice":true,"league":false}'::jsonb
    when 'player' then '{"admin":false,"games":true,"live":false,"analytics":false,"players":true,"scouting":false,"reports":false,"video":true,"gm":false,"recruitment":false,"practice":true,"league":false}'::jsonb
    else '{"admin":false,"games":true,"live":false,"analytics":true,"players":true,"scouting":true,"reports":true,"video":false,"gm":false,"recruitment":false,"practice":false,"league":false}'::jsonb
  end;
$$;

grant execute on function public.club_role_permissions(text) to authenticated;

create or replace function public.my_club_os_context()
returns jsonb
language sql stable security definer set search_path=public
as $$
  select coalesce(jsonb_agg(jsonb_build_object(
    'club', jsonb_build_object(
      'id', c.id, 'slug', c.slug, 'name', c.name, 'season', c.season,
      'country', c.country, 'competition', c.competition, 'pilot', c.pilot
    ),
    'role', m.role,
    'permissions', public.club_role_permissions(m.role) || coalesce(s.override_permissions,'{}'::jsonb),
    'seasons', coalesce(sx.seasons,'[]'::jsonb),
    'teams', coalesce(tx.teams,'[]'::jsonb)
  ) order by c.name),'[]'::jsonb)
  from public.club_members m
  join public.clubs c on c.id=m.club_id
  left join lateral (
    select coalesce(jsonb_object_agg(k,v),'{}'::jsonb) as override_permissions
    from (
      select e.key as k, e.value as v
      from public.club_member_scopes cms
      cross join lateral jsonb_each(cms.permissions) e
      where cms.club_id=m.club_id and cms.user_id=auth.uid()
      order by cms.id
    ) q
  ) s on true
  left join lateral (
    select jsonb_agg(jsonb_build_object(
      'id',cs.id,'season',cs.season,'competition',cs.competition,'country',cs.country,'is_active',cs.is_active
    ) order by cs.is_active desc,cs.season desc) as seasons
    from public.club_seasons cs where cs.club_id=m.club_id
  ) sx on true
  left join lateral (
    select jsonb_agg(jsonb_build_object(
      'id',ct.id,'season_id',ct.season_id,'name',ct.name,'code',ct.code,'gender',ct.gender,'level',ct.level,'is_primary',ct.is_primary
    ) order by ct.is_primary desc,ct.name) as teams
    from public.club_teams ct where ct.club_id=m.club_id
  ) tx on true
  where m.user_id=auth.uid();
$$;

revoke all on function public.my_club_os_context() from public;
grant execute on function public.my_club_os_context() to authenticated;

insert into public.club_seasons (club_id,season,competition,country,is_active)
select id, season, coalesce(competition,'Unknown'), country, true
from public.clubs
on conflict (club_id,season,competition) do update set is_active=excluded.is_active,country=excluded.country;

insert into public.club_teams (club_id,season_id,name,gender,level,is_primary)
select c.id,cs.id,c.name,'women','first_team',true
from public.clubs c
join public.club_seasons cs on cs.club_id=c.id and cs.season=c.season and cs.competition=coalesce(c.competition,'Unknown')
on conflict (club_id,season_id,name) do update set is_primary=true;
