-- CourtIQ SaaS Entitlements v216
-- Provider-neutral commercial layer: plan -> subscription -> usage -> hard limits.

create table if not exists public.saas_plans (
  plan_code text primary key,
  name text not null,
  monthly_game_limit integer,
  seat_limit integer,
  features jsonb not null default '{}'::jsonb,
  sort_order integer not null default 100,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  constraint saas_plans_game_limit_check check (monthly_game_limit is null or monthly_game_limit >= 0),
  constraint saas_plans_seat_limit_check check (seat_limit is null or seat_limit >= 1)
);

insert into public.saas_plans(plan_code,name,monthly_game_limit,seat_limit,features,sort_order,active)
values
  ('pilot','Pilot',null,null,'{"official_import":true,"scouting_report":true,"coach_brief":true,"season_memory":true,"player_memory":true,"live_intelligence":true,"video":true}'::jsonb,0,true),
  ('trial','Trial',20,2,'{"official_import":true,"scouting_report":true,"coach_brief":true,"season_memory":true,"player_memory":true,"live_intelligence":false,"video":false}'::jsonb,10,true),
  ('team','Team',150,6,'{"official_import":true,"scouting_report":true,"coach_brief":true,"season_memory":true,"player_memory":true,"live_intelligence":false,"video":false}'::jsonb,20,true),
  ('pro','Pro',600,20,'{"official_import":true,"scouting_report":true,"coach_brief":true,"season_memory":true,"player_memory":true,"live_intelligence":true,"video":true}'::jsonb,30,true),
  ('enterprise','Enterprise',null,null,'{"official_import":true,"scouting_report":true,"coach_brief":true,"season_memory":true,"player_memory":true,"live_intelligence":true,"video":true,"multi_team":true,"api":true}'::jsonb,40,true)
on conflict (plan_code) do update set
  name=excluded.name,
  monthly_game_limit=excluded.monthly_game_limit,
  seat_limit=excluded.seat_limit,
  features=excluded.features,
  sort_order=excluded.sort_order,
  active=excluded.active;

alter table public.saas_plans enable row level security;
drop policy if exists "authenticated read saas plans" on public.saas_plans;
create policy "authenticated read saas plans"
on public.saas_plans for select to authenticated
using (active = true);

create table if not exists public.club_subscriptions (
  id bigint generated by default as identity primary key,
  club_id bigint not null unique references public.clubs(id) on delete cascade,
  plan_code text not null references public.saas_plans(plan_code),
  status text not null default 'trialing',
  payment_provider text,
  provider_customer_id text,
  provider_subscription_id text,
  current_period_start timestamptz not null default now(),
  current_period_end timestamptz not null default (now() + interval '14 days'),
  trial_ends_at timestamptz,
  cancel_at_period_end boolean not null default false,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint club_subscriptions_status_check check (status in ('trialing','active','past_due','paused','canceled','incomplete'))
);

create unique index if not exists club_subscriptions_provider_subscription_uidx
  on public.club_subscriptions(payment_provider, provider_subscription_id)
  where payment_provider is not null and provider_subscription_id is not null;

alter table public.club_subscriptions enable row level security;
drop policy if exists "members read club subscription" on public.club_subscriptions;
create policy "members read club subscription"
on public.club_subscriptions for select to authenticated
using (private.is_club_member(club_id));

revoke insert, update, delete on public.club_subscriptions from anon, authenticated;

insert into public.club_subscriptions(
  club_id,plan_code,status,current_period_start,current_period_end,trial_ends_at,metadata
)
select
  c.id,
  case when c.pilot then 'pilot' else 'trial' end,
  case when c.pilot then 'active' else 'trialing' end,
  now(),
  case when c.pilot then now() + interval '10 years' else now() + interval '14 days' end,
  case when c.pilot then null else now() + interval '14 days' end,
  jsonb_build_object('source','migration_backfill')
from public.clubs c
on conflict (club_id) do nothing;

create or replace function private.courtiq_create_default_subscription()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  insert into public.club_subscriptions(
    club_id,plan_code,status,current_period_start,current_period_end,trial_ends_at,metadata
  ) values (
    new.id,
    case when new.pilot then 'pilot' else 'trial' end,
    case when new.pilot then 'active' else 'trialing' end,
    now(),
    case when new.pilot then now() + interval '10 years' else now() + interval '14 days' end,
    case when new.pilot then null else now() + interval '14 days' end,
    jsonb_build_object('source','club_create_trigger')
  )
  on conflict (club_id) do nothing;
  return new;
end;
$$;

revoke all on function private.courtiq_create_default_subscription() from public, anon, authenticated;

drop trigger if exists courtiq_create_default_subscription on public.clubs;
create trigger courtiq_create_default_subscription
after insert on public.clubs
for each row execute function private.courtiq_create_default_subscription();

create or replace function private.courtiq_touch_subscription()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  new.updated_at := now();
  return new;
end;
$$;

revoke all on function private.courtiq_touch_subscription() from public, anon, authenticated;

drop trigger if exists courtiq_touch_subscription on public.club_subscriptions;
create trigger courtiq_touch_subscription
before update on public.club_subscriptions
for each row execute function private.courtiq_touch_subscription();

create or replace view public.club_entitlement_status
with (security_invoker = true)
as
select
  s.club_id,
  s.plan_code,
  p.name as plan_name,
  s.status,
  s.payment_provider,
  s.current_period_start,
  s.current_period_end,
  s.trial_ends_at,
  s.cancel_at_period_end,
  p.monthly_game_limit,
  p.seat_limit,
  p.features,
  coalesce(u.games_used,0)::integer as games_used,
  case
    when p.monthly_game_limit is null then null
    else greatest(p.monthly_game_limit - coalesce(u.games_used,0)::integer,0)
  end as games_remaining,
  case
    when s.status not in ('active','trialing') then false
    when s.current_period_end <= now() then false
    when p.monthly_game_limit is null then true
    else coalesce(u.games_used,0) < p.monthly_game_limit
  end as can_import_game
from public.club_subscriptions s
join public.saas_plans p on p.plan_code = s.plan_code
left join lateral (
  select count(*) as games_used
  from public.games g
  where g.club_id = s.club_id
    and g.created_at >= s.current_period_start
    and g.created_at < s.current_period_end
) u on true;

comment on view public.club_entitlement_status is
  'Tenant-safe commercial entitlement and current-period usage snapshot.';

revoke all on public.club_entitlement_status from public, anon;
grant select on public.club_entitlement_status to authenticated;

create or replace function private.courtiq_enforce_game_entitlement()
returns trigger
language plpgsql
set search_path = ''
as $$
declare
  v_status text;
  v_limit integer;
  v_start timestamptz;
  v_end timestamptz;
  v_used integer;
begin
  if new.club_id is null then
    raise exception using errcode='P0001', message='COURTIQ_CLUB_REQUIRED';
  end if;

  -- Re-importing the same official game is an update, not additional usage.
  if exists (
    select 1 from public.games g
    where g.club_id = new.club_id
      and g.provider = new.provider
      and g.external_id = new.external_id
  ) then
    return new;
  end if;

  select s.status,p.monthly_game_limit,s.current_period_start,s.current_period_end
    into v_status,v_limit,v_start,v_end
  from public.club_subscriptions s
  join public.saas_plans p on p.plan_code=s.plan_code
  where s.club_id=new.club_id;

  if not found then
    raise exception using errcode='P0001', message='COURTIQ_SUBSCRIPTION_REQUIRED';
  end if;

  if v_status not in ('active','trialing') then
    raise exception using errcode='P0001', message='COURTIQ_SUBSCRIPTION_INACTIVE';
  end if;

  if v_end <= now() then
    raise exception using errcode='P0001', message='COURTIQ_BILLING_PERIOD_ENDED';
  end if;

  if v_limit is null then
    return new;
  end if;

  select count(*)::integer into v_used
  from public.games g
  where g.club_id=new.club_id
    and g.created_at >= v_start
    and g.created_at < v_end;

  if v_used >= v_limit then
    raise exception using errcode='P0001', message='COURTIQ_GAME_LIMIT_REACHED';
  end if;

  return new;
end;
$$;

revoke all on function private.courtiq_enforce_game_entitlement() from public, anon, authenticated;

drop trigger if exists courtiq_enforce_game_entitlement on public.games;
create trigger courtiq_enforce_game_entitlement
before insert on public.games
for each row execute function private.courtiq_enforce_game_entitlement();

create or replace function private.courtiq_enforce_seat_entitlement()
returns trigger
language plpgsql
set search_path = ''
as $$
declare
  v_limit integer;
  v_used integer;
begin
  if exists (
    select 1 from public.club_members cm
    where cm.club_id=new.club_id and cm.user_id=new.user_id
  ) then
    return new;
  end if;

  select p.seat_limit into v_limit
  from public.club_subscriptions s
  join public.saas_plans p on p.plan_code=s.plan_code
  where s.club_id=new.club_id and s.status in ('active','trialing');

  if v_limit is null then
    return new;
  end if;

  select count(*)::integer into v_used
  from public.club_members cm
  where cm.club_id=new.club_id;

  if v_used >= v_limit then
    raise exception using errcode='P0001', message='COURTIQ_SEAT_LIMIT_REACHED';
  end if;

  return new;
end;
$$;

revoke all on function private.courtiq_enforce_seat_entitlement() from public, anon, authenticated;

drop trigger if exists courtiq_enforce_seat_entitlement on public.club_members;
create trigger courtiq_enforce_seat_entitlement
before insert on public.club_members
for each row execute function private.courtiq_enforce_seat_entitlement();

create index if not exists games_club_created_at_idx on public.games(club_id,created_at desc);
